// Generated by scripts/generate-monaco-language-loaders.mjs from the installed monaco-editor package.
// Do not hand-edit Monaco language metadata here.

export interface MonacoLanguageMetadata {
  id: string;
  aliases?: readonly string[];
  extensions?: readonly string[];
  filenames?: readonly string[];
  filenamePatterns?: readonly string[];
  firstLine?: string;
  mimetypes?: readonly string[];
}

export const MONACO_LANGUAGE_METADATA = 
[
  {
    "id": "abap",
    "extensions": [
      ".abap"
    ],
    "aliases": [
      "ABAP",
      "abap"
    ]
  },
  {
    "id": "aes",
    "extensions": [
      ".aes"
    ],
    "aliases": [
      "Sophia",
      "aes",
      "sophia"
    ]
  },
  {
    "id": "apex",
    "extensions": [
      ".cls"
    ],
    "aliases": [
      "Apex",
      "apex"
    ],
    "mimetypes": [
      "text/x-apex",
      "text/x-apex-source"
    ]
  },
  {
    "id": "azcli",
    "extensions": [
      ".azcli"
    ],
    "aliases": [
      "Azure CLI",
      "azcli"
    ]
  },
  {
    "id": "bat",
    "extensions": [
      ".bat",
      ".cmd"
    ],
    "aliases": [
      "Batch",
      "bat"
    ]
  },
  {
    "id": "bicep",
    "extensions": [
      ".bicep"
    ],
    "aliases": [
      "Bicep"
    ]
  },
  {
    "id": "c",
    "extensions": [
      ".c",
      ".h"
    ],
    "aliases": [
      "C",
      "c"
    ]
  },
  {
    "id": "cameligo",
    "extensions": [
      ".mligo"
    ],
    "aliases": [
      "Cameligo"
    ]
  },
  {
    "id": "clojure",
    "extensions": [
      ".clj",
      ".cljc",
      ".cljs",
      ".edn"
    ],
    "aliases": [
      "Clojure",
      "clojure"
    ]
  },
  {
    "id": "coffeescript",
    "extensions": [
      ".coffee"
    ],
    "aliases": [
      "CoffeeScript",
      "coffee",
      "coffeescript"
    ],
    "mimetypes": [
      "text/coffeescript",
      "text/x-coffeescript"
    ]
  },
  {
    "id": "cpp",
    "extensions": [
      ".cc",
      ".cpp",
      ".cxx",
      ".hh",
      ".hpp",
      ".hxx"
    ],
    "aliases": [
      "C++",
      "Cpp",
      "cpp"
    ]
  },
  {
    "id": "csharp",
    "extensions": [
      ".cake",
      ".cs",
      ".csx"
    ],
    "aliases": [
      "C#",
      "csharp"
    ]
  },
  {
    "id": "csp",
    "extensions": [
      ".csp"
    ],
    "aliases": [
      "CSP",
      "csp"
    ]
  },
  {
    "id": "css",
    "extensions": [
      ".css"
    ],
    "aliases": [
      "CSS",
      "css"
    ],
    "mimetypes": [
      "text/css"
    ]
  },
  {
    "id": "cypher",
    "extensions": [
      ".cyp",
      ".cypher"
    ],
    "aliases": [
      "Cypher",
      "OpenCypher"
    ]
  },
  {
    "id": "dart",
    "extensions": [
      ".dart"
    ],
    "aliases": [
      "Dart",
      "dart"
    ],
    "mimetypes": [
      "text/x-dart",
      "text/x-dart-source"
    ]
  },
  {
    "id": "dockerfile",
    "extensions": [
      ".dockerfile"
    ],
    "filenames": [
      "Dockerfile"
    ],
    "aliases": [
      "Dockerfile"
    ]
  },
  {
    "id": "ecl",
    "extensions": [
      ".ecl"
    ],
    "aliases": [
      "ECL",
      "Ecl",
      "ecl"
    ]
  },
  {
    "id": "elixir",
    "extensions": [
      ".ex",
      ".exs"
    ],
    "aliases": [
      "Elixir",
      "elixir",
      "ex"
    ]
  },
  {
    "id": "flow9",
    "extensions": [
      ".flow"
    ],
    "aliases": [
      "Flow",
      "Flow9",
      "flow",
      "flow9"
    ]
  },
  {
    "id": "freemarker2",
    "extensions": [
      ".ftl",
      ".ftlh",
      ".ftlx"
    ],
    "aliases": [
      "Apache FreeMarker2",
      "FreeMarker2"
    ]
  },
  {
    "id": "freemarker2.tag-angle.interpolation-bracket",
    "aliases": [
      "Apache FreeMarker2 (Angle/Bracket)",
      "FreeMarker2 (Angle/Bracket)"
    ]
  },
  {
    "id": "freemarker2.tag-angle.interpolation-dollar",
    "aliases": [
      "Apache FreeMarker2 (Angle/Dollar)",
      "FreeMarker2 (Angle/Dollar)"
    ]
  },
  {
    "id": "freemarker2.tag-auto.interpolation-bracket",
    "aliases": [
      "Apache FreeMarker2 (Auto/Bracket)",
      "FreeMarker2 (Auto/Bracket)"
    ]
  },
  {
    "id": "freemarker2.tag-auto.interpolation-dollar",
    "aliases": [
      "Apache FreeMarker2 (Auto/Dollar)",
      "FreeMarker2 (Auto/Dollar)"
    ]
  },
  {
    "id": "freemarker2.tag-bracket.interpolation-bracket",
    "aliases": [
      "Apache FreeMarker2 (Bracket/Bracket)",
      "FreeMarker2 (Bracket/Bracket)"
    ]
  },
  {
    "id": "freemarker2.tag-bracket.interpolation-dollar",
    "aliases": [
      "Apache FreeMarker2 (Bracket/Dollar)",
      "FreeMarker2 (Bracket/Dollar)"
    ]
  },
  {
    "id": "fsharp",
    "extensions": [
      ".fs",
      ".fsi",
      ".fsscript",
      ".fsx",
      ".ml",
      ".mli"
    ],
    "aliases": [
      "F#",
      "FSharp",
      "fsharp"
    ]
  },
  {
    "id": "go",
    "extensions": [
      ".go"
    ],
    "aliases": [
      "Go"
    ]
  },
  {
    "id": "graphql",
    "extensions": [
      ".gql",
      ".graphql"
    ],
    "aliases": [
      "GraphQL",
      "gql",
      "graphql"
    ],
    "mimetypes": [
      "application/graphql"
    ]
  },
  {
    "id": "handlebars",
    "extensions": [
      ".handlebars",
      ".hbs"
    ],
    "aliases": [
      "Handlebars",
      "handlebars",
      "hbs"
    ],
    "mimetypes": [
      "text/x-handlebars-template"
    ]
  },
  {
    "id": "hcl",
    "extensions": [
      ".hcl",
      ".tf",
      ".tfvars"
    ],
    "aliases": [
      "HCL",
      "Terraform",
      "hcl",
      "tf"
    ]
  },
  {
    "id": "html",
    "extensions": [
      ".asp",
      ".aspx",
      ".htm",
      ".html",
      ".jshtm",
      ".jsp",
      ".mdoc",
      ".shtml",
      ".xhtml"
    ],
    "aliases": [
      "HTML",
      "htm",
      "html",
      "xhtml"
    ],
    "mimetypes": [
      "text/html",
      "text/ng-template",
      "text/template",
      "text/x-jshtm"
    ]
  },
  {
    "id": "ini",
    "extensions": [
      ".gitconfig",
      ".ini",
      ".properties"
    ],
    "filenames": [
      ".editorconfig",
      ".gitattributes",
      ".gitconfig",
      "config"
    ],
    "aliases": [
      "Ini",
      "ini"
    ]
  },
  {
    "id": "java",
    "extensions": [
      ".jav",
      ".java"
    ],
    "aliases": [
      "Java",
      "java"
    ],
    "mimetypes": [
      "text/x-java",
      "text/x-java-source"
    ]
  },
  {
    "id": "javascript",
    "extensions": [
      ".cjs",
      ".es6",
      ".js",
      ".jsx",
      ".mjs"
    ],
    "filenames": [
      "jakefile"
    ],
    "aliases": [
      "JavaScript",
      "javascript",
      "js"
    ],
    "mimetypes": [
      "text/javascript"
    ],
    "firstLine": "^#!.*\\\\bnode"
  },
  {
    "id": "json",
    "extensions": [
      ".babelrc",
      ".bowerrc",
      ".eslintrc",
      ".har",
      ".jscsrc",
      ".jshintrc",
      ".json"
    ],
    "aliases": [
      "JSON",
      "json"
    ],
    "mimetypes": [
      "application/json"
    ]
  },
  {
    "id": "julia",
    "extensions": [
      ".jl"
    ],
    "aliases": [
      "Julia",
      "julia"
    ]
  },
  {
    "id": "kotlin",
    "extensions": [
      ".kt",
      ".kts"
    ],
    "aliases": [
      "Kotlin",
      "kotlin"
    ],
    "mimetypes": [
      "text/x-kotlin",
      "text/x-kotlin-source"
    ]
  },
  {
    "id": "less",
    "extensions": [
      ".less"
    ],
    "aliases": [
      "Less",
      "less"
    ],
    "mimetypes": [
      "text/less",
      "text/x-less"
    ]
  },
  {
    "id": "lexon",
    "extensions": [
      ".lex"
    ],
    "aliases": [
      "Lexon"
    ]
  },
  {
    "id": "liquid",
    "extensions": [
      ".html.liquid",
      ".liquid"
    ],
    "aliases": [
      "Liquid",
      "liquid"
    ],
    "mimetypes": [
      "application/liquid"
    ]
  },
  {
    "id": "lua",
    "extensions": [
      ".lua"
    ],
    "aliases": [
      "Lua",
      "lua"
    ]
  },
  {
    "id": "m3",
    "extensions": [
      ".i3",
      ".ig",
      ".m3",
      ".mg"
    ],
    "aliases": [
      "Modula-3",
      "Modula3",
      "m3",
      "modula3"
    ]
  },
  {
    "id": "markdown",
    "extensions": [
      ".markdown",
      ".md",
      ".mdown",
      ".mdtext",
      ".mdtxt",
      ".mdwn",
      ".mkd",
      ".mkdn"
    ],
    "aliases": [
      "Markdown",
      "markdown"
    ]
  },
  {
    "id": "mdx",
    "extensions": [
      ".mdx"
    ],
    "aliases": [
      "MDX",
      "mdx"
    ]
  },
  {
    "id": "mips",
    "extensions": [
      ".s"
    ],
    "aliases": [
      "MIPS",
      "MIPS-V"
    ],
    "mimetypes": [
      "text/mips",
      "text/plaintext",
      "text/x-mips"
    ]
  },
  {
    "id": "msdax",
    "extensions": [
      ".dax",
      ".msdax"
    ],
    "aliases": [
      "DAX",
      "MSDAX"
    ]
  },
  {
    "id": "mysql",
    "aliases": [
      "MySQL",
      "mysql"
    ]
  },
  {
    "id": "objective-c",
    "extensions": [
      ".m"
    ],
    "aliases": [
      "Objective-C"
    ]
  },
  {
    "id": "pascal",
    "extensions": [
      ".p",
      ".pas",
      ".pp"
    ],
    "aliases": [
      "Pascal",
      "pas"
    ],
    "mimetypes": [
      "text/x-pascal",
      "text/x-pascal-source"
    ]
  },
  {
    "id": "pascaligo",
    "extensions": [
      ".ligo"
    ],
    "aliases": [
      "Pascaligo",
      "ligo"
    ]
  },
  {
    "id": "perl",
    "extensions": [
      ".pl",
      ".pm"
    ],
    "aliases": [
      "Perl",
      "pl"
    ]
  },
  {
    "id": "pgsql",
    "aliases": [
      "PostgreSQL",
      "pg",
      "postgre",
      "postgres"
    ]
  },
  {
    "id": "php",
    "extensions": [
      ".ctp",
      ".php",
      ".php4",
      ".php5",
      ".phtml"
    ],
    "aliases": [
      "PHP",
      "php"
    ],
    "mimetypes": [
      "application/x-php"
    ]
  },
  {
    "id": "pla",
    "extensions": [
      ".pla"
    ]
  },
  {
    "id": "postiats",
    "extensions": [
      ".dats",
      ".hats",
      ".sats"
    ],
    "aliases": [
      "ATS",
      "ATS/Postiats"
    ]
  },
  {
    "id": "powerquery",
    "extensions": [
      ".pq",
      ".pqm"
    ],
    "aliases": [
      "M",
      "PQ",
      "Power Query",
      "Power Query M"
    ]
  },
  {
    "id": "powershell",
    "extensions": [
      ".ps1",
      ".psd1",
      ".psm1"
    ],
    "aliases": [
      "PowerShell",
      "powershell",
      "ps",
      "ps1"
    ]
  },
  {
    "id": "proto",
    "extensions": [
      ".proto"
    ],
    "aliases": [
      "Protocol Buffers",
      "protobuf"
    ]
  },
  {
    "id": "pug",
    "extensions": [
      ".jade",
      ".pug"
    ],
    "aliases": [
      "Jade",
      "Pug",
      "jade"
    ]
  },
  {
    "id": "python",
    "extensions": [
      ".cpy",
      ".gyp",
      ".gypi",
      ".py",
      ".pyw",
      ".rpy"
    ],
    "aliases": [
      "Python",
      "py"
    ],
    "firstLine": "^#!/.*\\\\bpython[0-9.-]*\\\\b"
  },
  {
    "id": "qsharp",
    "extensions": [
      ".qs"
    ],
    "aliases": [
      "Q#",
      "qsharp"
    ]
  },
  {
    "id": "r",
    "extensions": [
      ".r",
      ".rhistory",
      ".rmd",
      ".rprofile",
      ".rt"
    ],
    "aliases": [
      "R",
      "r"
    ]
  },
  {
    "id": "razor",
    "extensions": [
      ".cshtml"
    ],
    "aliases": [
      "Razor",
      "razor"
    ],
    "mimetypes": [
      "text/x-cshtml"
    ]
  },
  {
    "id": "redis",
    "extensions": [
      ".redis"
    ],
    "aliases": [
      "redis"
    ]
  },
  {
    "id": "redshift",
    "aliases": [
      "Redshift",
      "redshift"
    ]
  },
  {
    "id": "restructuredtext",
    "extensions": [
      ".rst"
    ],
    "aliases": [
      "reStructuredText",
      "restructuredtext"
    ]
  },
  {
    "id": "ruby",
    "extensions": [
      ".gemspec",
      ".pp",
      ".rb",
      ".rbx",
      ".rjs"
    ],
    "filenames": [
      "Gemfile",
      "rakefile"
    ],
    "aliases": [
      "Ruby",
      "rb"
    ]
  },
  {
    "id": "rust",
    "extensions": [
      ".rlib",
      ".rs"
    ],
    "aliases": [
      "Rust",
      "rust"
    ]
  },
  {
    "id": "sb",
    "extensions": [
      ".sb"
    ],
    "aliases": [
      "Small Basic",
      "sb"
    ]
  },
  {
    "id": "scala",
    "extensions": [
      ".sbt",
      ".sc",
      ".scala"
    ],
    "aliases": [
      "Dotty",
      "SBT",
      "Sbt",
      "Scala",
      "dotty",
      "sbt",
      "scala"
    ],
    "mimetypes": [
      "text/x-dotty",
      "text/x-sbt",
      "text/x-scala",
      "text/x-scala-source"
    ]
  },
  {
    "id": "scheme",
    "extensions": [
      ".rkt",
      ".sch",
      ".scm",
      ".ss"
    ],
    "aliases": [
      "Scheme",
      "scheme"
    ]
  },
  {
    "id": "scss",
    "extensions": [
      ".scss"
    ],
    "aliases": [
      "Sass",
      "sass",
      "scss"
    ],
    "mimetypes": [
      "text/scss",
      "text/x-scss"
    ]
  },
  {
    "id": "shell",
    "extensions": [
      ".bash",
      ".sh"
    ],
    "aliases": [
      "Shell",
      "sh"
    ]
  },
  {
    "id": "sol",
    "extensions": [
      ".sol"
    ],
    "aliases": [
      "Solidity",
      "sol",
      "solidity"
    ]
  },
  {
    "id": "sparql",
    "extensions": [
      ".rq"
    ],
    "aliases": [
      "SPARQL",
      "sparql"
    ]
  },
  {
    "id": "sql",
    "extensions": [
      ".sql"
    ],
    "aliases": [
      "SQL"
    ]
  },
  {
    "id": "st",
    "extensions": [
      ".TcDUT",
      ".TcGVL",
      ".TcIO",
      ".TcPOU",
      ".iecplc",
      ".iecst",
      ".lc3lib",
      ".st"
    ],
    "aliases": [
      "StructuredText",
      "scl",
      "stl"
    ]
  },
  {
    "id": "swift",
    "extensions": [
      ".swift"
    ],
    "aliases": [
      "Swift",
      "swift"
    ],
    "mimetypes": [
      "text/swift"
    ]
  },
  {
    "id": "systemverilog",
    "extensions": [
      ".sv",
      ".svh"
    ],
    "aliases": [
      "SV",
      "SystemVerilog",
      "sv",
      "systemverilog"
    ]
  },
  {
    "id": "tcl",
    "extensions": [
      ".tcl"
    ],
    "aliases": [
      "Tcl",
      "Tcl/Tk",
      "TclTk",
      "tcl",
      "tcl/tk",
      "tcltk"
    ]
  },
  {
    "id": "twig",
    "extensions": [
      ".twig"
    ],
    "aliases": [
      "Twig",
      "twig"
    ],
    "mimetypes": [
      "text/x-twig"
    ]
  },
  {
    "id": "typescript",
    "extensions": [
      ".cts",
      ".mts",
      ".ts",
      ".tsx"
    ],
    "aliases": [
      "TypeScript",
      "ts",
      "typescript"
    ],
    "mimetypes": [
      "text/typescript"
    ]
  },
  {
    "id": "typespec",
    "extensions": [
      ".tsp"
    ],
    "aliases": [
      "TypeSpec"
    ]
  },
  {
    "id": "vb",
    "extensions": [
      ".vb"
    ],
    "aliases": [
      "Visual Basic",
      "vb"
    ]
  },
  {
    "id": "verilog",
    "extensions": [
      ".v",
      ".vh"
    ],
    "aliases": [
      "V",
      "Verilog",
      "v",
      "verilog"
    ]
  },
  {
    "id": "wgsl",
    "extensions": [
      ".wgsl"
    ],
    "aliases": [
      "WGSL",
      "WebGPU Shading Language",
      "wgsl"
    ]
  },
  {
    "id": "xml",
    "extensions": [
      ".ascx",
      ".config",
      ".csproj",
      ".dtd",
      ".opf",
      ".props",
      ".svg",
      ".svgz",
      ".targets",
      ".wxi",
      ".wxl",
      ".wxs",
      ".xaml",
      ".xml",
      ".xsd",
      ".xsl",
      ".xslt"
    ],
    "aliases": [
      "XML",
      "xml"
    ],
    "mimetypes": [
      "application/xaml+xml",
      "application/xml",
      "application/xml-dtd",
      "text/xml"
    ],
    "firstLine": "(\\\\<\\\\?xml.*)|(\\\\<svg)|(\\\\<\\\\!doctype\\\\s+svg)"
  },
  {
    "id": "yaml",
    "extensions": [
      ".yaml",
      ".yml"
    ],
    "aliases": [
      "YAML",
      "YML",
      "yaml",
      "yml"
    ],
    "mimetypes": [
      "application/x-yaml",
      "text/x-yaml"
    ]
  }
] as const satisfies readonly MonacoLanguageMetadata[];

