import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { StudioServerConfig } from "../../../../types/api.js";
import {
  CHANNEL_CONNECTORS_CC_BRIDGE_SERVICE_NAME,
  type CcBridgeConfigPreviewResponse,
  type CcBridgeLogsResponse,
  type CcBridgeServiceAction,
  type CcBridgeServiceCommand,
  type CcBridgeServiceCommandResult,
  type CcBridgeServiceManagerStatus,
  type CcBridgeServicePlan,
  type CcBridgeServiceRequest,
  type CcBridgeServiceResponse,
  type CcBridgeServiceTemplate,
  type ChannelConnectorsBindingPolicy,
  type ChannelConnectorsStatusResponse,
} from "../../../../types/channel-connectors.js";

const execFileAsync = promisify(execFile);
const CC_BRIDGE_ACTIONS: readonly CcBridgeServiceAction[] = [
  "preview",
  "install",
  "ensure-running",
  "start",
  "stop",
  "restart",
  "status",
];
const LOG_MAX_SIZE_BYTES = 10 * 1024 * 1024;

export type CcBridgeServiceCommandRunner = (
  command: CcBridgeServiceCommand,
) => Promise<CcBridgeServiceCommandResult>;

export type CcBridgeBinaryResolver = (command: string) => string | null;

export interface ChannelConnectorsServiceOptions {
  homeDir?: string;
  ccConnectBinary?: string;
  commandRunner?: CcBridgeServiceCommandRunner;
  binaryResolver?: CcBridgeBinaryResolver;
  now?: () => Date;
}

export interface ChannelConnectorsService {
  getStatus(): Promise<ChannelConnectorsStatusResponse>;
  getCcBridgeConfig(): CcBridgeConfigPreviewResponse;
  getCcBridgeService(): Promise<CcBridgeServiceResponse>;
  manageCcBridgeService(payload?: CcBridgeServiceRequest): Promise<CcBridgeServiceResponse>;
  getCcBridgeLogs(limit?: number): CcBridgeLogsResponse;
}

interface CcBridgePaths {
  rootDir: string;
  configPath: string;
  stateDir: string;
  logDir: string;
  logFile: string;
  runtimeFile: string;
}

function normalizeHomeDir(value: string | undefined): string {
  const trimmed = String(value || "").trim();
  return trimmed || os.homedir();
}

export function resolveChannelConnectorsPaths(
  config: StudioServerConfig,
): CcBridgePaths {
  const rootDir = path.join(config.openclawRoot, "studio", "channel-connectors", "cc-bridge");
  const logDir = path.join(rootDir, "logs");
  return {
    rootDir,
    configPath: path.join(rootDir, "config.toml"),
    stateDir: path.join(rootDir, "state"),
    logDir,
    logFile: path.join(logDir, "cc-bridge.log"),
    runtimeFile: path.join(rootDir, "runtime.json"),
  };
}

function readTextIfExists(filePath: string): string | null {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return null;
    throw error;
  }
}

function ensureParentDir(filePath: string): void {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function writeTextAtomic(filePath: string, content: string): void {
  ensureParentDir(filePath);
  const tempPath = `${filePath}.tmp-${process.pid}-${Date.now()}`;
  fs.writeFileSync(tempPath, content, "utf8");
  fs.renameSync(tempPath, filePath);
}

function normalizeServiceAction(value: unknown): CcBridgeServiceAction {
  return CC_BRIDGE_ACTIONS.includes(value as CcBridgeServiceAction)
    ? value as CcBridgeServiceAction
    : "preview";
}

function escapeTomlString(value: string): string {
  return JSON.stringify(value);
}

function quoteSystemdArg(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function quoteLaunchdString(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function gatewayEndpoint(): string {
  return "http://127.0.0.1:18796/v1";
}

function buildConfigPreview(config: StudioServerConfig, paths: CcBridgePaths, now: Date): CcBridgeConfigPreviewResponse {
  const workDir = config.projectRoot || process.cwd();
  const preview = [
    `# Generated by OpenClaw Studio at ${now.toISOString()}`,
    `data_dir = ${escapeTomlString(paths.stateDir)}`,
    `language = "zh"`,
    "",
    "[log]",
    `level = "info"`,
    "",
    "[management]",
    "enabled = true",
    "port = 9820",
    `token = "\${STUDIO_CC_BRIDGE_MANAGEMENT_TOKEN}"`,
    "",
    "[[providers]]",
    `name = "studio-gateway"`,
    `api_key = "\${STUDIO_GATEWAY_CLIENT_KEY}"`,
    `base_url = ${escapeTomlString(gatewayEndpoint())}`,
    `agent_types = ["codex", "claudecode", "opencode"]`,
    "",
    "[[projects]]",
    `name = "default"`,
    "",
    "[projects.agent]",
    `type = "codex"`,
    `provider_refs = ["studio-gateway"]`,
    "",
    "[projects.agent.options]",
    `work_dir = ${escapeTomlString(workDir)}`,
    `mode = "suggest"`,
    "",
    "# F2/F3 will add one or more [[projects.platforms]] entries.",
    "# cc-connect validates at least one platform before the daemon can start.",
    "",
  ].join("\n");

  return {
    ok: true,
    checkedAt: now.toISOString(),
    ready: false,
    configPath: paths.configPath,
    gatewayEndpoint: gatewayEndpoint(),
    preview,
    missing: ["projects.platforms"],
  };
}

function resolveBinaryFromPath(command: string): string | null {
  const trimmed = command.trim();
  if (!trimmed) return null;
  if (trimmed.includes(path.sep)) {
    return fs.existsSync(trimmed) ? trimmed : null;
  }
  const entries = String(process.env.PATH || "")
    .split(path.delimiter)
    .filter(Boolean);
  for (const entry of entries) {
    const candidate = path.join(entry, trimmed);
    if (fs.existsSync(candidate)) return candidate;
    if (process.platform === "win32" && fs.existsSync(`${candidate}.exe`)) return `${candidate}.exe`;
  }
  return null;
}

function buildSystemdTemplate(serviceName: string, paths: CcBridgePaths, binaryPath: string | null): string {
  const executable = binaryPath || "cc-connect";
  return [
    "[Unit]",
    "Description=OpenClaw Studio CC Bridge",
    "After=network-online.target",
    "Wants=network-online.target",
    "",
    "[Service]",
    "Type=simple",
    `WorkingDirectory=${quoteSystemdArg(paths.rootDir)}`,
    `ExecStart=${quoteSystemdArg(executable)} -config ${quoteSystemdArg(paths.configPath)}`,
    "Restart=on-failure",
    "RestartSec=10",
    `Environment=${quoteSystemdArg(`CC_LOG_FILE=${paths.logFile}`)}`,
    `Environment=${quoteSystemdArg(`CC_LOG_MAX_SIZE=${LOG_MAX_SIZE_BYTES}`)}`,
    `Environment=${quoteSystemdArg(`OPENAI_BASE_URL=${gatewayEndpoint()}`)}`,
    "",
    "[Install]",
    "WantedBy=default.target",
    "",
  ].join("\n");
}

function buildLaunchdTemplate(serviceName: string, paths: CcBridgePaths, binaryPath: string | null): string {
  const executable = binaryPath || "cc-connect";
  return [
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
    "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
    "<plist version=\"1.0\">",
    "<dict>",
    "  <key>Label</key>",
    `  <string>${quoteLaunchdString(serviceName.replace(/\.service$/, ""))}</string>`,
    "  <key>ProgramArguments</key>",
    "  <array>",
    `    <string>${quoteLaunchdString(executable)}</string>`,
    "    <string>-config</string>",
    `    <string>${quoteLaunchdString(paths.configPath)}</string>`,
    "  </array>",
    "  <key>WorkingDirectory</key>",
    `  <string>${quoteLaunchdString(paths.rootDir)}</string>`,
    "  <key>RunAtLoad</key>",
    "  <true/>",
    "  <key>KeepAlive</key>",
    "  <true/>",
    "  <key>EnvironmentVariables</key>",
    "  <dict>",
    "    <key>CC_LOG_FILE</key>",
    `    <string>${quoteLaunchdString(paths.logFile)}</string>`,
    "    <key>CC_LOG_MAX_SIZE</key>",
    `    <string>${LOG_MAX_SIZE_BYTES}</string>`,
    "    <key>OPENAI_BASE_URL</key>",
    `    <string>${quoteLaunchdString(gatewayEndpoint())}</string>`,
    "  </dict>",
    "</dict>",
    "</plist>",
    "",
  ].join("\n");
}

export function createCcBridgeServicePlan(
  config: StudioServerConfig,
  options: ChannelConnectorsServiceOptions = {},
): CcBridgeServicePlan {
  const paths = resolveChannelConnectorsPaths(config);
  const homeDir = normalizeHomeDir(options.homeDir);
  const binaryCommand = String(options.ccConnectBinary || process.env.OPENCLAW_STUDIO_CC_CONNECT_BIN || "cc-connect").trim();
  const binaryPath = options.binaryResolver
    ? options.binaryResolver(binaryCommand)
    : resolveBinaryFromPath(binaryCommand);
  const binary = {
    command: binaryCommand,
    path: binaryPath,
    available: Boolean(binaryPath),
    source: process.env.OPENCLAW_STUDIO_CC_CONNECT_BIN ? "env" as const : (binaryPath ? "path" as const : "missing" as const),
  };

  const serviceName = CHANNEL_CONNECTORS_CC_BRIDGE_SERVICE_NAME;
  const platform = process.platform === "linux"
    ? "linux"
    : process.platform === "darwin"
      ? "macos"
      : process.platform === "win32"
        ? "windows"
        : "unknown";
  const supervisor = platform === "linux"
    ? "systemd-user"
    : platform === "macos"
      ? "launchd-user"
      : platform === "windows"
        ? "scheduled-task"
        : "none";

  const linuxServicePath = path.join(homeDir, ".config", "systemd", "user", serviceName);
  const launchdServicePath = path.join(homeDir, "Library", "LaunchAgents", serviceName.replace(/\.service$/, ".plist"));
  const unsupportedServicePath = path.join(paths.rootDir, serviceName);
  const launchdDomain = typeof process.getuid === "function" ? `gui/${process.getuid()}` : "gui/501";
  const launchdLabel = serviceName.replace(/\.service$/, "");

  const linuxTemplate = {
    supervisor: "systemd-user" as const,
    platform: "linux" as const,
    serviceName,
    servicePath: linuxServicePath,
    template: buildSystemdTemplate(serviceName, paths, binaryPath),
    commands: {
      install: [
        { label: "Reload user systemd", command: "systemctl", args: ["--user", "daemon-reload"] },
        { label: "Enable CC Bridge service", command: "systemctl", args: ["--user", "enable", serviceName] },
      ],
      start: [
        { label: "Start CC Bridge service", command: "systemctl", args: ["--user", "start", serviceName] },
      ],
      stop: [
        { label: "Stop CC Bridge service", command: "systemctl", args: ["--user", "stop", serviceName] },
      ],
      restart: [
        { label: "Restart CC Bridge service", command: "systemctl", args: ["--user", "restart", serviceName] },
      ],
      status: [
        { label: "Check CC Bridge active state", command: "systemctl", args: ["--user", "is-active", serviceName] },
        { label: "Check CC Bridge enabled state", command: "systemctl", args: ["--user", "is-enabled", serviceName] },
      ],
      "ensure-running": [
        { label: "Reload user systemd", command: "systemctl", args: ["--user", "daemon-reload"] },
        { label: "Enable CC Bridge service", command: "systemctl", args: ["--user", "enable", serviceName] },
        { label: "Start CC Bridge service", command: "systemctl", args: ["--user", "start", serviceName] },
      ],
    },
  };
  const launchdTemplate = {
    supervisor: "launchd-user" as const,
    platform: "macos" as const,
    serviceName,
    servicePath: launchdServicePath,
    template: buildLaunchdTemplate(serviceName, paths, binaryPath),
    commands: {
      install: [
        { label: "Bootstrap LaunchAgent", command: "launchctl", args: ["bootstrap", launchdDomain, launchdServicePath] },
      ],
      start: [
        { label: "Start LaunchAgent", command: "launchctl", args: ["kickstart", "-k", `${launchdDomain}/${launchdLabel}`] },
      ],
      stop: [
        { label: "Stop LaunchAgent", command: "launchctl", args: ["bootout", launchdDomain, launchdServicePath] },
      ],
      restart: [
        { label: "Restart LaunchAgent", command: "launchctl", args: ["kickstart", "-k", `${launchdDomain}/${launchdLabel}`] },
      ],
      status: [
        { label: "Print LaunchAgent", command: "launchctl", args: ["print", `${launchdDomain}/${launchdLabel}`] },
      ],
    },
  };
  const unsupportedTemplate: CcBridgeServiceTemplate = {
    supervisor,
    platform,
    serviceName,
    servicePath: unsupportedServicePath,
    template: "# Unsupported platform for Studio-managed CC Bridge service.\n",
    commands: {},
  };

  const templates = [linuxTemplate, launchdTemplate, unsupportedTemplate];
  const selectedTemplate = platform === "linux"
    ? linuxTemplate
    : platform === "macos"
      ? launchdTemplate
      : unsupportedTemplate;

  const notes = [
    "CC Bridge is managed as a daemon separate from Studio Gateway.",
    "Studio and OpenClaw are not runtime dependencies once the service is running.",
  ];
  if (!binary.available) notes.push("cc-connect binary was not found; install/start actions are blocked.");
  if (platform === "windows") notes.push("Windows scheduled-task installation will be added with the managed cc-connect fork.");

  return {
    platform: process.platform,
    supported: platform === "linux" || platform === "macos",
    supervisor,
    serviceName,
    binary,
    rootDir: paths.rootDir,
    configPath: paths.configPath,
    stateDir: paths.stateDir,
    logFile: paths.logFile,
    runtimeFile: paths.runtimeFile,
    selectedTemplate,
    templates,
    notes,
  };
}

async function runDefaultCommand(command: CcBridgeServiceCommand): Promise<CcBridgeServiceCommandResult> {
  try {
    const result = await execFileAsync(command.command, command.args, {
      timeout: 30_000,
      encoding: "utf8",
    });
    return {
      ...command,
      ok: true,
      exitCode: 0,
      stdout: result.stdout || "",
      stderr: result.stderr || "",
      error: null,
    };
  } catch (error) {
    const shaped = error as Error & {
      code?: string | number;
      stdout?: string;
      stderr?: string;
    };
    return {
      ...command,
      ok: false,
      exitCode: typeof shaped.code === "number" ? shaped.code : null,
      stdout: shaped.stdout || "",
      stderr: shaped.stderr || "",
      error: shaped.message || "Command failed.",
    };
  }
}

function summarizeServiceManager(
  plan: CcBridgeServicePlan,
  commandsRun: CcBridgeServiceCommandResult[],
): CcBridgeServiceManagerStatus {
  if (!plan.supported) {
    return {
      checked: true,
      reachable: false,
      active: null,
      enabled: null,
      lastError: "Supervisor is not supported on this platform yet.",
    };
  }
  const statusCommands = commandsRun.filter((result) => {
    const args = result.args.join(" ");
    return args.includes("is-active")
      || args.includes("is-enabled")
      || result.label.toLowerCase().includes("active")
      || result.label.toLowerCase().includes("enabled")
      || result.command === "launchctl";
  });
  if (!statusCommands.length) {
    return {
      checked: false,
      reachable: null,
      active: null,
      enabled: null,
      lastError: null,
    };
  }
  const activeResult = statusCommands.find((result) => result.args.includes("is-active"));
  const enabledResult = statusCommands.find((result) => result.args.includes("is-enabled"));
  const lastFailed = [...statusCommands].reverse().find((result) => !result.ok);
  return {
    checked: true,
    reachable: statusCommands.some((result) => result.ok),
    active: activeResult ? activeResult.ok && activeResult.stdout.trim() === "active" : null,
    enabled: enabledResult ? enabledResult.ok && enabledResult.stdout.trim() === "enabled" : null,
    lastError: lastFailed?.stderr || lastFailed?.error || null,
  };
}

function isTemplateCurrent(plan: CcBridgeServicePlan): boolean {
  return readTextIfExists(plan.selectedTemplate.servicePath) === plan.selectedTemplate.template;
}

function isConfigCurrent(configPreview: CcBridgeConfigPreviewResponse): boolean {
  return readTextIfExists(configPreview.configPath) === configPreview.preview;
}

function shouldWriteTemplate(action: CcBridgeServiceAction): boolean {
  return action === "install" || action === "ensure-running" || action === "start" || action === "restart";
}

function serviceActionRequiresReadyConfig(action: CcBridgeServiceAction): boolean {
  return action === "install" || action === "ensure-running" || action === "start" || action === "restart";
}

function blockingReason(plan: CcBridgeServicePlan, configPreview: CcBridgeConfigPreviewResponse, action: CcBridgeServiceAction): string | null {
  if (action === "preview" || action === "status" || action === "stop") return null;
  if (!plan.supported) return "unsupported_supervisor";
  if (!plan.binary.available) return "cc_connect_binary_missing";
  if (serviceActionRequiresReadyConfig(action) && !configPreview.ready) return "cc_bridge_config_incomplete";
  return null;
}

function tailLines(filePath: string, limit: number): { exists: boolean; lines: string[] } {
  const raw = readTextIfExists(filePath);
  if (raw === null) return { exists: false, lines: [] };
  const normalizedLimit = Math.max(1, Math.min(500, Math.floor(limit || 120)));
  const lines = raw.split(/\r?\n/);
  return {
    exists: true,
    lines: lines.slice(Math.max(0, lines.length - normalizedLimit)).filter((line) => line.length > 0),
  };
}

function bindingPolicy(): ChannelConnectorsBindingPolicy {
  return {
    model: "platform-account-or-bot-to-agent",
    supportedAgents: ["codex", "claude-code", "opencode"],
    supportedPlatforms: ["octo", "feishu", "wechat", "wecom"],
    multiBot: {
      allowed: true,
      unit: "platform-account-or-bot",
    },
    wechatPersonal: {
      maxAgentsPerAccount: 1,
    },
  };
}

export function createChannelConnectorsService(
  config: StudioServerConfig,
  options: ChannelConnectorsServiceOptions = {},
): ChannelConnectorsService {
  const now = () => (options.now ? options.now() : new Date());
  const runCommand = (command: CcBridgeServiceCommand) =>
    options.commandRunner ? options.commandRunner(command) : runDefaultCommand(command);

  function currentConfigPreview(): CcBridgeConfigPreviewResponse {
    return buildConfigPreview(config, resolveChannelConnectorsPaths(config), now());
  }

  async function serviceResponse(
    input: {
      action: CcBridgeServiceAction;
      applied?: boolean;
      templateWritten?: boolean;
      configWritten?: boolean;
      commandsRun?: CcBridgeServiceCommandResult[];
      skippedReason?: string | null;
      diagnostics?: string[];
    },
  ): Promise<CcBridgeServiceResponse> {
    const plan = createCcBridgeServicePlan(config, options);
    const configPreview = currentConfigPreview();
    const commandsRun = input.commandsRun || [];
    const installed = fs.existsSync(plan.selectedTemplate.servicePath);
    const serviceManager = summarizeServiceManager(plan, commandsRun);
    return {
      ok: input.skippedReason ? false : commandsRun.every((result) => result.ok),
      checkedAt: now().toISOString(),
      action: input.action,
      applied: input.applied === true,
      templateWritten: input.templateWritten === true,
      configWritten: input.configWritten === true,
      templateCurrent: isTemplateCurrent(plan),
      configCurrent: isConfigCurrent(configPreview),
      installed,
      skippedReason: input.skippedReason || null,
      plan,
      config: configPreview,
      commandsRun,
      serviceManager,
      diagnostics: input.diagnostics || [],
    };
  }

  async function runStatusCommands(plan: CcBridgeServicePlan): Promise<CcBridgeServiceCommandResult[]> {
    const commands = plan.selectedTemplate.commands.status || [];
    const results: CcBridgeServiceCommandResult[] = [];
    for (const command of commands) results.push(await runCommand(command));
    return results;
  }

  async function getCcBridgeService(): Promise<CcBridgeServiceResponse> {
    const plan = createCcBridgeServicePlan(config, options);
    const commandsRun = plan.supported ? await runStatusCommands(plan) : [];
    return serviceResponse({
      action: "status",
      commandsRun,
    });
  }

  async function manageCcBridgeService(payload: CcBridgeServiceRequest = {}): Promise<CcBridgeServiceResponse> {
    const action = normalizeServiceAction(payload.action);
    const plan = createCcBridgeServicePlan(config, options);
    const configPreview = currentConfigPreview();
    const guard = blockingReason(plan, configPreview, action);
    const diagnostics: string[] = [];
    if (guard === "cc_connect_binary_missing") {
      diagnostics.push("Install cc-connect or set OPENCLAW_STUDIO_CC_CONNECT_BIN before managing the service.");
    }
    if (guard === "cc_bridge_config_incomplete") {
      diagnostics.push("Add at least one platform binding before enabling the CC Bridge daemon.");
    }
    if (guard === "unsupported_supervisor") {
      diagnostics.push("The current OS supervisor is not supported by Studio-managed CC Bridge F1.");
    }
    if (guard) {
      return serviceResponse({
        action,
        skippedReason: guard,
        diagnostics,
      });
    }

    const apply = payload.apply === true;
    let templateWritten = false;
    let configWritten = false;
    if (apply && shouldWriteTemplate(action)) {
      fs.mkdirSync(plan.rootDir, { recursive: true });
      fs.mkdirSync(plan.stateDir, { recursive: true });
      fs.mkdirSync(path.dirname(plan.logFile), { recursive: true });
      if (!isConfigCurrent(configPreview)) {
        writeTextAtomic(configPreview.configPath, configPreview.preview);
        configWritten = true;
      }
      if (!isTemplateCurrent(plan)) {
        writeTextAtomic(plan.selectedTemplate.servicePath, plan.selectedTemplate.template);
        templateWritten = true;
      }
    }

    const commandsRun: CcBridgeServiceCommandResult[] = [];
    const shouldRunCommands = payload.runCommands === true
      || (payload.runCommands !== false && apply && action !== "preview" && action !== "status");
    if (action === "status") {
      commandsRun.push(...await runStatusCommands(plan));
    } else if (shouldRunCommands) {
      const commands = plan.selectedTemplate.commands[action] || [];
      for (const command of commands) commandsRun.push(await runCommand(command));
      if (action !== "stop") commandsRun.push(...await runStatusCommands(plan));
    }

    return serviceResponse({
      action,
      applied: templateWritten || configWritten || commandsRun.length > 0,
      templateWritten,
      configWritten,
      commandsRun,
      diagnostics,
    });
  }

  async function getStatus(): Promise<ChannelConnectorsStatusResponse> {
    const service = await getCcBridgeService();
    return {
      ok: true,
      checkedAt: now().toISOString(),
      phase: "f1-service-control",
      runtimeChain: [
        "IM channel",
        "CC Bridge daemon",
        "local Agent CLI",
        "Studio Gateway daemon",
        "upstream provider",
      ],
      bindingPolicy: bindingPolicy(),
      paths: {
        root: service.plan.rootDir,
        config: service.plan.configPath,
        state: service.plan.stateDir,
        log: service.plan.logFile,
        runtime: service.plan.runtimeFile,
      },
      lifecycle: {
        studioRuntimeDependency: false,
        openclawRuntimeDependency: false,
        modelRelayOwner: "studio-gateway-daemon",
        ccBridgeOwner: "cc-bridge-daemon",
      },
      service,
    };
  }

  function getCcBridgeLogs(limit = 120): CcBridgeLogsResponse {
    const paths = resolveChannelConnectorsPaths(config);
    const log = tailLines(paths.logFile, limit);
    return {
      ok: true,
      checkedAt: now().toISOString(),
      logFile: paths.logFile,
      exists: log.exists,
      lines: log.lines,
    };
  }

  return {
    getStatus,
    getCcBridgeConfig: currentConfigPreview,
    getCcBridgeService,
    manageCcBridgeService,
    getCcBridgeLogs,
  };
}
