// Generated by scripts/generate-monaco-language-loaders.mjs from the installed monaco-editor package.
// Do not hand-edit language coverage here; update the generator when Monaco packaging changes.

import * as monaco from "monaco-editor/esm/vs/editor/editor.api.js";

export type MonacoLanguageLoader = () => Promise<unknown>;

type MonacoBasicLanguageModule = {
  conf?: monaco.languages.LanguageConfiguration;
  language?: monaco.languages.IMonarchLanguage;
};

async function installMonacoBasicLanguage(
  languageId: string,
  loadContribution: () => Promise<unknown>,
  loadLanguage: () => Promise<MonacoBasicLanguageModule>,
): Promise<unknown> {
  const [contribution, languageModule] = await Promise.all([loadContribution(), loadLanguage()]);
  if (languageModule.conf) monaco.languages.setLanguageConfiguration(languageId, languageModule.conf);
  if (languageModule.language) monaco.languages.setMonarchTokensProvider(languageId, languageModule.language);
  return { contribution, languageModule };
}

export const MONACO_BASIC_LANGUAGE_LOADERS: Record<string, MonacoLanguageLoader> = {
  "abap": () => installMonacoBasicLanguage("abap", () => import("monaco-editor/esm/vs/basic-languages/abap/abap.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/abap/abap.js")),
  "aes": () => installMonacoBasicLanguage("aes", () => import("monaco-editor/esm/vs/basic-languages/sophia/sophia.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/sophia/sophia.js")),
  "apex": () => installMonacoBasicLanguage("apex", () => import("monaco-editor/esm/vs/basic-languages/apex/apex.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/apex/apex.js")),
  "azcli": () => installMonacoBasicLanguage("azcli", () => import("monaco-editor/esm/vs/basic-languages/azcli/azcli.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/azcli/azcli.js")),
  "bat": () => installMonacoBasicLanguage("bat", () => import("monaco-editor/esm/vs/basic-languages/bat/bat.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/bat/bat.js")),
  "bicep": () => installMonacoBasicLanguage("bicep", () => import("monaco-editor/esm/vs/basic-languages/bicep/bicep.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/bicep/bicep.js")),
  "c": () => installMonacoBasicLanguage("c", () => import("monaco-editor/esm/vs/basic-languages/cpp/cpp.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/cpp/cpp.js")),
  "cameligo": () => installMonacoBasicLanguage("cameligo", () => import("monaco-editor/esm/vs/basic-languages/cameligo/cameligo.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/cameligo/cameligo.js")),
  "clojure": () => installMonacoBasicLanguage("clojure", () => import("monaco-editor/esm/vs/basic-languages/clojure/clojure.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/clojure/clojure.js")),
  "coffeescript": () => installMonacoBasicLanguage("coffeescript", () => import("monaco-editor/esm/vs/basic-languages/coffee/coffee.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/coffee/coffee.js")),
  "cpp": () => installMonacoBasicLanguage("cpp", () => import("monaco-editor/esm/vs/basic-languages/cpp/cpp.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/cpp/cpp.js")),
  "csharp": () => installMonacoBasicLanguage("csharp", () => import("monaco-editor/esm/vs/basic-languages/csharp/csharp.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/csharp/csharp.js")),
  "csp": () => installMonacoBasicLanguage("csp", () => import("monaco-editor/esm/vs/basic-languages/csp/csp.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/csp/csp.js")),
  "css": () => installMonacoBasicLanguage("css", () => import("monaco-editor/esm/vs/basic-languages/css/css.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/css/css.js")),
  "cypher": () => installMonacoBasicLanguage("cypher", () => import("monaco-editor/esm/vs/basic-languages/cypher/cypher.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/cypher/cypher.js")),
  "dart": () => installMonacoBasicLanguage("dart", () => import("monaco-editor/esm/vs/basic-languages/dart/dart.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/dart/dart.js")),
  "dockerfile": () => installMonacoBasicLanguage("dockerfile", () => import("monaco-editor/esm/vs/basic-languages/dockerfile/dockerfile.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/dockerfile/dockerfile.js")),
  "ecl": () => installMonacoBasicLanguage("ecl", () => import("monaco-editor/esm/vs/basic-languages/ecl/ecl.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/ecl/ecl.js")),
  "elixir": () => installMonacoBasicLanguage("elixir", () => import("monaco-editor/esm/vs/basic-languages/elixir/elixir.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/elixir/elixir.js")),
  "flow9": () => installMonacoBasicLanguage("flow9", () => import("monaco-editor/esm/vs/basic-languages/flow9/flow9.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/flow9/flow9.js")),
  "freemarker2": () => installMonacoBasicLanguage("freemarker2", () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.js")),
  "freemarker2.tag-angle.interpolation-bracket": () => installMonacoBasicLanguage("freemarker2.tag-angle.interpolation-bracket", () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.js")),
  "freemarker2.tag-angle.interpolation-dollar": () => installMonacoBasicLanguage("freemarker2.tag-angle.interpolation-dollar", () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.js")),
  "freemarker2.tag-auto.interpolation-bracket": () => installMonacoBasicLanguage("freemarker2.tag-auto.interpolation-bracket", () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.js")),
  "freemarker2.tag-auto.interpolation-dollar": () => installMonacoBasicLanguage("freemarker2.tag-auto.interpolation-dollar", () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.js")),
  "freemarker2.tag-bracket.interpolation-bracket": () => installMonacoBasicLanguage("freemarker2.tag-bracket.interpolation-bracket", () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.js")),
  "freemarker2.tag-bracket.interpolation-dollar": () => installMonacoBasicLanguage("freemarker2.tag-bracket.interpolation-dollar", () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/freemarker2/freemarker2.js")),
  "fsharp": () => installMonacoBasicLanguage("fsharp", () => import("monaco-editor/esm/vs/basic-languages/fsharp/fsharp.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/fsharp/fsharp.js")),
  "go": () => installMonacoBasicLanguage("go", () => import("monaco-editor/esm/vs/basic-languages/go/go.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/go/go.js")),
  "graphql": () => installMonacoBasicLanguage("graphql", () => import("monaco-editor/esm/vs/basic-languages/graphql/graphql.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/graphql/graphql.js")),
  "handlebars": () => installMonacoBasicLanguage("handlebars", () => import("monaco-editor/esm/vs/basic-languages/handlebars/handlebars.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/handlebars/handlebars.js")),
  "hcl": () => installMonacoBasicLanguage("hcl", () => import("monaco-editor/esm/vs/basic-languages/hcl/hcl.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/hcl/hcl.js")),
  "html": () => installMonacoBasicLanguage("html", () => import("monaco-editor/esm/vs/basic-languages/html/html.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/html/html.js")),
  "ini": () => installMonacoBasicLanguage("ini", () => import("monaco-editor/esm/vs/basic-languages/ini/ini.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/ini/ini.js")),
  "java": () => installMonacoBasicLanguage("java", () => import("monaco-editor/esm/vs/basic-languages/java/java.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/java/java.js")),
  "javascript": () => installMonacoBasicLanguage("javascript", () => import("monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/javascript/javascript.js")),
  "julia": () => installMonacoBasicLanguage("julia", () => import("monaco-editor/esm/vs/basic-languages/julia/julia.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/julia/julia.js")),
  "kotlin": () => installMonacoBasicLanguage("kotlin", () => import("monaco-editor/esm/vs/basic-languages/kotlin/kotlin.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/kotlin/kotlin.js")),
  "less": () => installMonacoBasicLanguage("less", () => import("monaco-editor/esm/vs/basic-languages/less/less.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/less/less.js")),
  "lexon": () => installMonacoBasicLanguage("lexon", () => import("monaco-editor/esm/vs/basic-languages/lexon/lexon.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/lexon/lexon.js")),
  "liquid": () => installMonacoBasicLanguage("liquid", () => import("monaco-editor/esm/vs/basic-languages/liquid/liquid.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/liquid/liquid.js")),
  "lua": () => installMonacoBasicLanguage("lua", () => import("monaco-editor/esm/vs/basic-languages/lua/lua.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/lua/lua.js")),
  "m3": () => installMonacoBasicLanguage("m3", () => import("monaco-editor/esm/vs/basic-languages/m3/m3.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/m3/m3.js")),
  "markdown": () => installMonacoBasicLanguage("markdown", () => import("monaco-editor/esm/vs/basic-languages/markdown/markdown.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/markdown/markdown.js")),
  "mdx": () => installMonacoBasicLanguage("mdx", () => import("monaco-editor/esm/vs/basic-languages/mdx/mdx.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/mdx/mdx.js")),
  "mips": () => installMonacoBasicLanguage("mips", () => import("monaco-editor/esm/vs/basic-languages/mips/mips.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/mips/mips.js")),
  "msdax": () => installMonacoBasicLanguage("msdax", () => import("monaco-editor/esm/vs/basic-languages/msdax/msdax.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/msdax/msdax.js")),
  "mysql": () => installMonacoBasicLanguage("mysql", () => import("monaco-editor/esm/vs/basic-languages/mysql/mysql.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/mysql/mysql.js")),
  "objective-c": () => installMonacoBasicLanguage("objective-c", () => import("monaco-editor/esm/vs/basic-languages/objective-c/objective-c.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/objective-c/objective-c.js")),
  "pascal": () => installMonacoBasicLanguage("pascal", () => import("monaco-editor/esm/vs/basic-languages/pascal/pascal.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/pascal/pascal.js")),
  "pascaligo": () => installMonacoBasicLanguage("pascaligo", () => import("monaco-editor/esm/vs/basic-languages/pascaligo/pascaligo.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/pascaligo/pascaligo.js")),
  "perl": () => installMonacoBasicLanguage("perl", () => import("monaco-editor/esm/vs/basic-languages/perl/perl.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/perl/perl.js")),
  "pgsql": () => installMonacoBasicLanguage("pgsql", () => import("monaco-editor/esm/vs/basic-languages/pgsql/pgsql.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/pgsql/pgsql.js")),
  "php": () => installMonacoBasicLanguage("php", () => import("monaco-editor/esm/vs/basic-languages/php/php.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/php/php.js")),
  "pla": () => installMonacoBasicLanguage("pla", () => import("monaco-editor/esm/vs/basic-languages/pla/pla.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/pla/pla.js")),
  "postiats": () => installMonacoBasicLanguage("postiats", () => import("monaco-editor/esm/vs/basic-languages/postiats/postiats.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/postiats/postiats.js")),
  "powerquery": () => installMonacoBasicLanguage("powerquery", () => import("monaco-editor/esm/vs/basic-languages/powerquery/powerquery.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/powerquery/powerquery.js")),
  "powershell": () => installMonacoBasicLanguage("powershell", () => import("monaco-editor/esm/vs/basic-languages/powershell/powershell.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/powershell/powershell.js")),
  "proto": () => installMonacoBasicLanguage("proto", () => import("monaco-editor/esm/vs/basic-languages/protobuf/protobuf.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/protobuf/protobuf.js")),
  "pug": () => installMonacoBasicLanguage("pug", () => import("monaco-editor/esm/vs/basic-languages/pug/pug.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/pug/pug.js")),
  "python": () => installMonacoBasicLanguage("python", () => import("monaco-editor/esm/vs/basic-languages/python/python.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/python/python.js")),
  "qsharp": () => installMonacoBasicLanguage("qsharp", () => import("monaco-editor/esm/vs/basic-languages/qsharp/qsharp.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/qsharp/qsharp.js")),
  "r": () => installMonacoBasicLanguage("r", () => import("monaco-editor/esm/vs/basic-languages/r/r.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/r/r.js")),
  "razor": () => installMonacoBasicLanguage("razor", () => import("monaco-editor/esm/vs/basic-languages/razor/razor.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/razor/razor.js")),
  "redis": () => installMonacoBasicLanguage("redis", () => import("monaco-editor/esm/vs/basic-languages/redis/redis.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/redis/redis.js")),
  "redshift": () => installMonacoBasicLanguage("redshift", () => import("monaco-editor/esm/vs/basic-languages/redshift/redshift.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/redshift/redshift.js")),
  "restructuredtext": () => installMonacoBasicLanguage("restructuredtext", () => import("monaco-editor/esm/vs/basic-languages/restructuredtext/restructuredtext.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/restructuredtext/restructuredtext.js")),
  "ruby": () => installMonacoBasicLanguage("ruby", () => import("monaco-editor/esm/vs/basic-languages/ruby/ruby.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/ruby/ruby.js")),
  "rust": () => installMonacoBasicLanguage("rust", () => import("monaco-editor/esm/vs/basic-languages/rust/rust.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/rust/rust.js")),
  "sb": () => installMonacoBasicLanguage("sb", () => import("monaco-editor/esm/vs/basic-languages/sb/sb.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/sb/sb.js")),
  "scala": () => installMonacoBasicLanguage("scala", () => import("monaco-editor/esm/vs/basic-languages/scala/scala.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/scala/scala.js")),
  "scheme": () => installMonacoBasicLanguage("scheme", () => import("monaco-editor/esm/vs/basic-languages/scheme/scheme.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/scheme/scheme.js")),
  "scss": () => installMonacoBasicLanguage("scss", () => import("monaco-editor/esm/vs/basic-languages/scss/scss.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/scss/scss.js")),
  "shell": () => installMonacoBasicLanguage("shell", () => import("monaco-editor/esm/vs/basic-languages/shell/shell.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/shell/shell.js")),
  "sol": () => installMonacoBasicLanguage("sol", () => import("monaco-editor/esm/vs/basic-languages/solidity/solidity.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/solidity/solidity.js")),
  "sparql": () => installMonacoBasicLanguage("sparql", () => import("monaco-editor/esm/vs/basic-languages/sparql/sparql.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/sparql/sparql.js")),
  "sql": () => installMonacoBasicLanguage("sql", () => import("monaco-editor/esm/vs/basic-languages/sql/sql.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/sql/sql.js")),
  "st": () => installMonacoBasicLanguage("st", () => import("monaco-editor/esm/vs/basic-languages/st/st.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/st/st.js")),
  "swift": () => installMonacoBasicLanguage("swift", () => import("monaco-editor/esm/vs/basic-languages/swift/swift.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/swift/swift.js")),
  "systemverilog": () => installMonacoBasicLanguage("systemverilog", () => import("monaco-editor/esm/vs/basic-languages/systemverilog/systemverilog.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/systemverilog/systemverilog.js")),
  "tcl": () => installMonacoBasicLanguage("tcl", () => import("monaco-editor/esm/vs/basic-languages/tcl/tcl.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/tcl/tcl.js")),
  "twig": () => installMonacoBasicLanguage("twig", () => import("monaco-editor/esm/vs/basic-languages/twig/twig.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/twig/twig.js")),
  "typescript": () => installMonacoBasicLanguage("typescript", () => import("monaco-editor/esm/vs/basic-languages/typescript/typescript.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/typescript/typescript.js")),
  "typespec": () => installMonacoBasicLanguage("typespec", () => import("monaco-editor/esm/vs/basic-languages/typespec/typespec.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/typespec/typespec.js")),
  "vb": () => installMonacoBasicLanguage("vb", () => import("monaco-editor/esm/vs/basic-languages/vb/vb.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/vb/vb.js")),
  "verilog": () => installMonacoBasicLanguage("verilog", () => import("monaco-editor/esm/vs/basic-languages/systemverilog/systemverilog.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/systemverilog/systemverilog.js")),
  "wgsl": () => installMonacoBasicLanguage("wgsl", () => import("monaco-editor/esm/vs/basic-languages/wgsl/wgsl.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/wgsl/wgsl.js")),
  "xml": () => installMonacoBasicLanguage("xml", () => import("monaco-editor/esm/vs/basic-languages/xml/xml.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/xml/xml.js")),
  "yaml": () => installMonacoBasicLanguage("yaml", () => import("monaco-editor/esm/vs/basic-languages/yaml/yaml.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/yaml/yaml.js")),
};

export const MONACO_RICH_LANGUAGE_LOADERS: Record<string, MonacoLanguageLoader> = {
  "css": () => Promise.all([installMonacoBasicLanguage("css", () => import("monaco-editor/esm/vs/basic-languages/css/css.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/css/css.js")), import("monaco-editor/esm/vs/language/css/monaco.contribution.js")]),
  "html": () => Promise.all([installMonacoBasicLanguage("html", () => import("monaco-editor/esm/vs/basic-languages/html/html.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/html/html.js")), import("monaco-editor/esm/vs/language/html/monaco.contribution.js")]),
  "json": () => Promise.all([import("monaco-editor/esm/vs/language/json/monaco.contribution.js")]),
  "typescript": () => Promise.all([installMonacoBasicLanguage("typescript", () => import("monaco-editor/esm/vs/basic-languages/typescript/typescript.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/typescript/typescript.js")), import("monaco-editor/esm/vs/language/typescript/monaco.contribution.js")]),
};

export const MONACO_RICH_LANGUAGE_ALIAS_LOADERS: Record<string, MonacoLanguageLoader> = {
  "handlebars": () => Promise.all([installMonacoBasicLanguage("handlebars", () => import("monaco-editor/esm/vs/basic-languages/handlebars/handlebars.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/handlebars/handlebars.js")), import("monaco-editor/esm/vs/language/html/monaco.contribution.js")]),
  "javascript": () => Promise.all([installMonacoBasicLanguage("javascript", () => import("monaco-editor/esm/vs/basic-languages/javascript/javascript.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/javascript/javascript.js")), import("monaco-editor/esm/vs/language/typescript/monaco.contribution.js")]),
  "less": () => Promise.all([installMonacoBasicLanguage("less", () => import("monaco-editor/esm/vs/basic-languages/less/less.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/less/less.js")), import("monaco-editor/esm/vs/language/css/monaco.contribution.js")]),
  "razor": () => Promise.all([installMonacoBasicLanguage("razor", () => import("monaco-editor/esm/vs/basic-languages/razor/razor.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/razor/razor.js")), import("monaco-editor/esm/vs/language/html/monaco.contribution.js")]),
  "scss": () => Promise.all([installMonacoBasicLanguage("scss", () => import("monaco-editor/esm/vs/basic-languages/scss/scss.contribution.js"), () => import("monaco-editor/esm/vs/basic-languages/scss/scss.js")), import("monaco-editor/esm/vs/language/css/monaco.contribution.js")]),
};

export const MONACO_LANGUAGE_LOADERS: Record<string, MonacoLanguageLoader> = {
  ...MONACO_BASIC_LANGUAGE_LOADERS,
  ...MONACO_RICH_LANGUAGE_LOADERS,
  ...MONACO_RICH_LANGUAGE_ALIAS_LOADERS,
};

export const MONACO_LANGUAGE_LOADER_COUNTS = {
  basic: 89,
  rich: 4,
  richAliases: 5,
  total: 90,
} as const;

