import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");

function read(filePath) {
  return fs.readFileSync(path.join(rootDir, filePath), "utf8");
}

const routeManifest = read("apps/web-vue/src/features/shell/route-manifest.ts");
const managementManifest = read("apps/web-vue/src/features/management/management-domain-manifest.ts");
const filesView = read("apps/web-vue/src/views/FilesView.vue");
const filesControlPage = read("apps/web-vue/src/features/files/FilesControlPage.vue");
const codeFileEditor = read("apps/web-vue/src/features/files/CodeFileEditor.vue");
const filesApi = read("apps/web-vue/src/features/files/api.ts");
const filesDriver = read("apps/web-vue/src/features/files/vuefinder-driver.ts");
const filesRoutes = read("apps/api/modules/files/routes.ts");
const main = read("apps/web-vue/src/main.ts");

test("files route and management domain are wired into Studio shell", () => {
  assert.match(routeManifest, /const FilesView = \(\) => import\("\.\.\/\.\.\/views\/FilesView\.vue"\)/);
  assert.match(routeManifest, /path:\s*"\/files"/);
  assert.match(routeManifest, /key:\s*"files"/);
  assert.match(routeManifest, /icon:\s*"files"/);
  assert.match(managementManifest, /id:\s*"files"/);
  assert.match(managementManifest, /routePath:\s*"\/files"/);
  assert.match(filesView, /FilesControlPage/);
  assert.match(filesView, /getManagementDomainEntry\("files"\)/);
});

test("files workspace exposes explorer layout, tree, listing, editor, upload, and maintenance actions", () => {
  assert.match(filesControlPage, /文件管理器|File manager/);
  assert.match(filesControlPage, /VueFinder/);
  assert.doesNotMatch(filesControlPage, /file-manager-chrome__tabs/);
  assert.doesNotMatch(filesControlPage, /file-manager-chrome__addressbar/);
  assert.doesNotMatch(filesControlPage, /goToAddress/);
  assert.doesNotMatch(filesControlPage, /useVueFinder/);
  assert.match(filesControlPage, /visibleRoots/);
  assert.match(filesControlPage, /root\.id !== "project-root"/);
  assert.match(filesControlPage, /storageRoots/);
  assert.match(filesControlPage, /storageNameForRoot/);
  assert.match(filesControlPage, /locale\.value === "zh" \? "zhCN" : "en"/);
  assert.match(filesControlPage, /OpenClaw 根目录/);
  assert.match(filesControlPage, /用户目录/);
  assert.match(filesControlPage, /系统根目录/);
  assert.match(filesControlPage, /studio-file-explorer/);
  assert.match(filesControlPage, /StudioFilesVueFinderDriver/);
  assert.match(filesControlPage, /AsyncCodeFileEditor/);
  assert.match(filesControlPage, /file-manager-editor-drawer--maximized/);
  assert.match(filesControlPage, /editorTabs/);
  assert.match(filesControlPage, /activeEditorId/);
  assert.match(filesControlPage, /file-manager-editor-sidebar/);
  assert.match(filesControlPage, /当前目录/);
  assert.match(filesControlPage, /editorDirectoryEntries/);
  assert.match(filesControlPage, /browseDirectory/);
  assert.match(filesControlPage, /openEditorForEntry/);
  assert.match(filesControlPage, /搜索\/替换/);
  assert.match(filesControlPage, /file-manager-editor-drawer__statusbar/);
  assert.match(filesControlPage, /editorLineCount/);
  assert.match(filesControlPage, /editorLanguageLabel/);
  assert.match(filesControlPage, /resolvedTheme/);
  assert.match(filesControlPage, /theme:\s*resolvedTheme\.value === "light" \? "silver" : "midnight"/);
  assert.match(filesControlPage, /html\[data-theme="dark"\] \.file-manager-page/);
  assert.match(filesControlPage, /handleFileDclick/);
  assert.match(filesControlPage, /handleExplorerPathChange/);
  assert.match(filesControlPage, /openEditorForItem/);
  assert.match(filesControlPage, /saveEditor/);
  assert.match(filesControlPage, /file-manager-statusbar/);
  assert.match(filesControlPage, /refreshExplorer/);
  assert.match(filesControlPage, /handleFileManagerKeydown/);
  assert.match(filesControlPage, /quickCreateDirectory/);
  assert.match(filesControlPage, /quickCreateFile/);
  assert.match(filesControlPage, /fileClipboard/);
  assert.match(filesControlPage, /putSelectedItemsOnClipboard/);
  assert.match(filesControlPage, /pasteFileClipboardIntoCurrentDirectory/);
  assert.match(filesControlPage, /copySelectedPathsToClipboard/);
  assert.match(filesControlPage, /writeTextToSystemClipboard/);
  assert.match(filesControlPage, /duplicateSelectedItems/);
  assert.match(filesControlPage, /file-manager-details/);
  assert.match(filesControlPage, /openDetailsForSelection/);
  assert.match(filesControlPage, /formatFileSize/);
  assert.match(filesControlPage, /studio_show_details/);
  assert.match(filesControlPage, /studio_duplicate/);
  assert.match(filesControlPage, /studio_quick_copy/);
  assert.match(filesControlPage, /studio_quick_cut/);
  assert.match(filesControlPage, /studio_quick_paste/);
  assert.match(filesControlPage, /studio_copy_path/);
  assert.match(filesControlPage, /file-manager-view-controls/);
  assert.match(filesControlPage, /explorerUiPrefs/);
  assert.match(filesControlPage, /FILE_MANAGER_UI_STORAGE_KEY/);
  assert.match(filesControlPage, /toggleExplorerUi/);
  assert.match(filesControlPage, /cycleExplorerDensity/);
  assert.match(filesControlPage, /showMenuBar:\s*explorerUiPrefs\.value\.menuBar/);
  assert.match(filesControlPage, /showToolbar:\s*explorerUiPrefs\.value\.toolbar/);
  assert.match(filesControlPage, /showTreeView:\s*explorerUiPrefs\.value\.treeView/);
  assert.match(filesControlPage, /showThumbnails:\s*explorerUiPrefs\.value\.thumbnails/);
  assert.match(filesControlPage, /gridIconSize/);
  assert.match(filesControlPage, /listIconSize/);
  assert.match(filesControlPage, /studio-file-icon/);
  assert.match(filesControlPage, /#icon/);
  assert.match(filesControlPage, /explorerItemIconKind/);
  assert.match(filesControlPage, /selectedCodeFiles/);
  assert.match(filesControlPage, /openEditorForItems/);
  assert.match(filesControlPage, /selectedArchiveTarget/);
  assert.match(filesControlPage, /studio_download_archive/);
  assert.match(filesControlPage, /downloadArchiveForItems/);
  assert.doesNotMatch(filesControlPage, /PROPERTIES|选中项属性/);
  assert.doesNotMatch(filesControlPage, /file-manager-inspector-grid/);
  assert.match(filesControlPage, /context-menu-items/);
  assert.match(filesControlPage, /studio_open_in_editor/);
  assert.match(filesControlPage, /explorerFeatures/);
  assert.match(filesControlPage, /explorerConfig/);
  assert.match(filesControlPage, /handleExplorerError/);
  assert.match(filesControlPage, /handleNotify/);
  assert.match(filesDriver, /extends BaseAdapter/);
  assert.match(filesDriver, /StudioFileStorageRoot/);
  assert.match(filesDriver, /toVueFinderPath/);
  assert.match(filesDriver, /resolvePath/);
  assert.match(filesDriver, /configureUploader/);
  assert.match(filesDriver, /browseDirectory/);
  assert.match(filesDriver, /searchFiles/);
  assert.match(filesDriver, /saveFileContent/);
  assert.match(filesDriver, /uploadFiles/);
  assert.match(filesDriver, /archivePaths/);
  assert.match(filesDriver, /unarchiveFile/);
  assert.match(codeFileEditor, /CodeMirror|EditorView|codemirror/);
  assert.match(codeFileEditor, /loadLanguageExtension/);
  assert.match(codeFileEditor, /applyLanguageExtension/);
  assert.match(codeFileEditor, /openSearchPanel/);
  assert.match(codeFileEditor, /searchRequest/);
  assert.match(codeFileEditor, /backgroundColor:\s*"#0b1220"/);
  assert.match(codeFileEditor, /scrollPastEnd/);
  assert.match(codeFileEditor, /rectangularSelection/);
  assert.match(codeFileEditor, /key:\s*"Mod-s"/);
  assert.match(codeFileEditor, /emit\("save"\)/);
  assert.match(codeFileEditor, /scrollbar-width:\s*thin/);
  assert.match(codeFileEditor, /oneDark/);
  assert.match(main, /VueFinderPlugin/);
  assert.match(main, /vuefinder\/dist\/vuefinder\.css/);
});

test("files api and server routes cover browse, tree, read, search, mutate, upload, and download", () => {
  assert.match(filesApi, /fetchFilesSummary/);
  assert.match(filesApi, /browseDirectory/);
  assert.match(filesApi, /fetchDirectoryTree/);
  assert.match(filesApi, /readFileContent/);
  assert.match(filesApi, /searchFiles/);
  assert.match(filesApi, /createDirectory/);
  assert.match(filesApi, /createFile/);
  assert.match(filesApi, /saveFileContent/);
  assert.match(filesApi, /renamePath/);
  assert.match(filesApi, /copyPath/);
  assert.match(filesApi, /movePath/);
  assert.match(filesApi, /deletePaths/);
  assert.match(filesApi, /uploadFiles/);
  assert.match(filesApi, /archivePaths/);
  assert.match(filesApi, /unarchiveFile/);
  assert.match(filesApi, /buildArchiveDownloadUrl/);
  assert.match(filesApi, /buildFileDownloadUrl/);
  assert.match(filesRoutes, /\/api\/files\/summary/);
  assert.match(filesRoutes, /\/api\/files\/browse/);
  assert.match(filesRoutes, /\/api\/files\/tree/);
  assert.match(filesRoutes, /\/api\/files\/read/);
  assert.match(filesRoutes, /\/api\/files\/search/);
  assert.match(filesRoutes, /\/api\/files\/download/);
  assert.match(filesRoutes, /\/api\/files\/upload/);
  assert.match(filesRoutes, /\/api\/files\/archive/);
  assert.match(filesRoutes, /\/api\/files\/unarchive/);
  assert.match(filesRoutes, /\/api\/files\/download-archive/);
  assert.match(read("types/files.ts"), /matchKind\?: "name" \| "content"/);
  assert.match(read("apps/api/modules/files/service.ts"), /findContentSearchSnippet/);
});
