import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const rootDir = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../..");

function read(relativePath) {
  return fs.readFileSync(path.join(rootDir, relativePath), "utf8");
}

test("Channel Connector profiles page is wired outside OpenClaw Agents", () => {
  const routeManifest = read("apps/web-vue/src/features/shell/route-manifest.ts");
  const layout = read("apps/web-vue/src/features/agents/AgentsWorkspaceLayout.vue");
  const agentsIndex = read("apps/web-vue/src/features/agents/index.ts");
  const channelIndex = read("apps/web-vue/src/features/channel-connectors/index.ts");

  assert.match(routeManifest, /const ChannelConnectorAgentProfilesPage = \(\) =>\s*import\("\.\.\/channel-connectors\/ChannelConnectorAgentProfilesPage\.vue"\)/);
  assert.match(routeManifest, /ChannelConnectorAgentProfilesPage,/);
  assert.match(routeManifest, /path:\s*"\/channel-connectors\/profiles",\s*component:\s*ChannelConnectorAgentProfilesPage/);
  assert.doesNotMatch(routeManifest, /AgentCliPage/);
  assert.doesNotMatch(routeManifest, /path:\s*":agentId\/cli"/);
  assert.doesNotMatch(layout, /type AgentTaskSection = 'overview' \| 'cli'/);
  assert.doesNotMatch(layout, /label:\s*'CLI'/);
  assert.doesNotMatch(layout, /\/agents\/\$\{encoded\}\/cli/);
  assert.doesNotMatch(agentsIndex, /AgentCliPage/);
  assert.match(channelIndex, /ChannelConnectorAgentProfilesPage/);
});

test("Channel Connector profiles page edits profiles using Gateway model catalog", () => {
  const page = read("apps/web-vue/src/features/channel-connectors/ChannelConnectorAgentProfilesPage.vue");
  const styles = read("apps/web-vue/src/features/channel-connectors/channel-connectors-workspace.css");
  const connectorsPage = read("apps/web-vue/src/features/channel-connectors/ChannelConnectorsControlPage.vue");

  assert.match(page, /fetchModelGatewayAppConnections/);
  assert.match(page, /fetchModelGatewayProviders/);
  assert.match(page, /appConnectionsResponse\.availableModels/);
  assert.match(page, /appConnections\.value = appConnectionsResponse\.connections/);
  assert.match(page, /collectGatewayProviderModelNames/);
  assert.match(page, /model\.aliases/);
  assert.match(page, /profileModelLabel\(profile\)/);
  assert.match(page, /function effectiveModelForProfile/);
  assert.match(page, /appConnectionProfile\.value\?\.appModels\?\.\[appId\]/);
  assert.match(page, /inherits \$\{model\}/);
  assert.match(page, /fetchChannelConnectorsNativeConfig/);
  assert.match(page, /saveChannelConnectorsNativeConfig/);
  assert.match(page, /fetchChannelConnectorAgentSessions/);
  assert.match(page, /manageChannelConnectorAgentSessions/);
  assert.match(page, /CLI Profile 管理/);
  assert.match(page, /Gateway Endpoint/);
  assert.match(page, /IM Bindings/);
  assert.match(page, /Sessions and records/);
  assert.match(page, /ccx-agent-profile-rail/);
  assert.match(page, /ccx-agent-profile-main/);
  assert.match(page, /ccx-agent-profile-activity/);
  assert.match(page, /ccx-agent-profile-config-section/);
  assert.match(page, /Model and context/);
  assert.match(page, /Budget source/);
  assert.match(page, /Context window/);
  assert.match(page, /Auto compact/);
  assert.match(page, /CLI App 连接|CLI App connection/);
  assert.match(page, /selectedAppConnection/);
  assert.match(page, /selectedAppConnectionModel/);
  assert.match(page, /ccx-agent-profile-app-facts/);
  assert.match(page, /selectedAppConnection\?\.target\.path/);
  assert.match(page, /selectedAppConnection\?\.lastBackupPath/);
  assert.match(page, /selectedAppConnection\?\.launchHint/);
  assert.match(page, /selectedAppConnection\?\.preview\?\.content/);
  assert.match(page, /selectedAppConnection\.preview\.content/);
  assert.match(page, /selectedAppConnectionIssues/);
  assert.match(page, /canApplySelectedAppConnection/);
  assert.match(page, /selectedAppConnectionApplyDisabledReason/);
  assert.match(page, /applySelectedAppConnection/);
  assert.match(page, /applyModelGatewayAppConnection/);
  assert.match(page, /currentAppConnectionProfilePatch/);
  assert.match(page, /const effectiveModel = selectedEffectiveModel\.value \|\| null/);
  assert.match(page, /\[appId\]: effectiveModel/);
  assert.match(page, /refreshAppConnectionCatalog/);
  assert.match(page, /应用到 CLI|Apply to CLI/);
  assert.match(page, /App 连接|App connection/);
  assert.match(page, /selectedEffectiveModel = computed/);
  assert.match(page, /profileDraft\.model \|\| selectedAppConnectionModel\.value \|\| appConnectionProfile\.value\?\.model/);
  assert.match(page, /modelGatewayAppConnectionIdForAgent/);
  assert.match(page, /appProfileOptions/);
  assert.match(page, /default · Gateway App Connections/);
  assert.match(page, /模型网关|Model Gateway/);
  assert.match(page, /打开配置|Open config/);
  assert.match(page, /openBindingConfig/);
  assert.match(page, /bindingId:\s*binding\.id/);
  assert.match(page, /profileId:\s*binding\.agentProfileId/);
  assert.match(page, /sessionDriverLabel\(binding\.id\)/);
  assert.match(page, /function sessionDriverLabel/);
  assert.match(page, /agentSessions\.value\?\.bindings\.find/);
  assert.match(page, /openBindingConfigById/);
  assert.match(page, /openBindingConfigById\(session\.bindingId\)/);
  assert.match(page, /openBindingConfigById\(event\.bindingId\)/);
  assert.match(page, /openSelectedProfileConfig/);
  assert.match(page, /profileId \? \{ profileId \} : \{\}/);
  assert.match(page, /事件筛选|Event filter/);
  assert.match(page, /requestedSessions\.length/);
  assert.match(page, /ccx-agent-profile-requested-list/);
  assert.match(page, /ccx-agent-profile-requested-row/);
  assert.match(page, /session\.effectiveMode/);
  assert.match(page, /session\.requestedMode/);
  assert.match(page, /session\.reason/);
  assert.match(page, /ccx-agent-profile-session-trace/);
  assert.match(page, /session\.projectId/);
  assert.match(page, /session\.sessionKey/);
  assert.match(page, /session\.poolKey/);
  assert.match(page, /session\.turnCount/);
  assert.match(page, /formatDuration\(session\.idleMs\)/);
  assert.match(page, /openBindingConfigById\(session\.bindingId\)/);
  assert.match(page, /停止全部|Stop all/);
  assert.match(page, /撤销|Discard/);
  assert.match(page, /duplicateProfile/);
  assert.match(page, /deleteProfile/);
  assert.match(page, /canDeleteSelectedProfile/);
  assert.match(page, /deleteProfileDisabledReason/);
  assert.match(page, /selectedProfileFromConfig/);
  assert.match(page, /selectedProfileLookupIds/);
  assert.match(page, /profileIdConflict/);
  assert.match(page, /profileIdChanged/);
  assert.match(page, /hasUnsavedProfileChanges/);
  assert.match(page, /canSaveProfile/);
  assert.match(page, /saveProfileDisabledReason/);
  assert.match(page, /discardProfileChanges/);
  assert.match(page, /persistProfileDraftToConfig/);
  assert.match(page, /previousProfileId/);
  assert.match(page, /binding\.agentProfileId = profile\.id/);
  assert.match(page, /allRelatedSessionEvents/);
  assert.match(page, /eventFilterOptions/);
  assert.match(page, /eventLimitOptions/);
  assert.match(page, /filteredRelatedSessionEvents/);
  assert.match(page, /relatedSessionEventCountLabel/);
  assert.match(page, /relatedSessionEvents = computed\(\(\) => filteredRelatedSessionEvents\.value\.slice\(0, relatedSessionEventLimit\.value\)\)/);
  assert.match(page, /ccx-agent-profile-event-trace/);
  assert.match(page, /event\.sessionKey/);
  assert.match(page, /event\.messageId/);
  assert.match(page, /compactPath\(event\.workDir\)/);
  assert.match(page, /danger: Boolean\(event\.error\)/);
  assert.match(page, /killActiveSessions/);
  assert.match(page, /openModelGateway/);
  assert.match(page, /path:\s*'\/model-gateway'/);
  assert.match(page, /query:\s*appId \? \{ tab: 'connections', app: appId \} : \{ tab: 'connections' \}/);
  assert.match(page, /appConnectionProfile/);
  assert.match(page, /gatewayModelBudgetIndex/);
  assert.match(page, /deriveAutoCompactTokenLimit/);
  assert.doesNotMatch(page, /fetchAgentDetail|fetchAgentsSummary|AgentDetailPayload/);
  assert.match(styles, /\.ccx-agent-profile-layout/);
  assert.match(styles, /\.ccx-agent-profile-rail/);
  assert.match(styles, /\.ccx-agent-profile-main/);
  assert.match(styles, /\.ccx-agent-profile-activity/);
  assert.match(styles, /\.ccx-agent-profile-config-section/);
  assert.match(styles, /\.ccx-agent-profile-budget-strip/);
  assert.match(styles, /\.ccx-agent-profile-app-connection/);
  assert.match(styles, /\.ccx-agent-profile-app-facts/);
  assert.match(styles, /\.ccx-agent-profile-app-issues/);
  assert.match(styles, /\.ccx-agent-profile-app-actions/);
  assert.match(styles, /\.ccx-agent-profile-app-preview/);
  assert.match(styles, /white-space: pre-wrap/);
  assert.match(styles, /\.ccx-agent-profile-binding-main/);
  assert.match(styles, /\.ccx-agent-profile-requested-list/);
  assert.match(styles, /\.ccx-agent-profile-requested-row/);
  assert.match(styles, /\.ccx-agent-profile-linked-row/);
  assert.match(styles, /\.ccx-agent-profile-session-trace/);
  assert.match(styles, /\.ccx-agent-profile-event-row\.danger/);
  assert.match(styles, /\.ccx-agent-profile-event-trace/);
  assert.match(styles, /\.ccx-agent-profile-row-actions/);
  assert.match(styles, /\.ccx-agent-profile-select-row/);
  assert.match(styles, /\.ccx-agent-profile-editor-actions/);
  assert.match(styles, /\.ccx-agent-profile-edit-state/);
  assert.match(styles, /\.ccx-agent-profile-session-toolbar/);
  assert.match(styles, /grid-template-columns: minmax\(180px, 240px\) minmax\(120px, 160px\) minmax\(0, 1fr\)/);
  assert.match(styles, /\.ccx-field-button/);
  assert.doesNotMatch(styles, /\.agents-cli-/);
  assert.match(connectorsPage, /profileWorkspaceRoute/);
  assert.match(connectorsPage, /path:\s*'\/channel-connectors\/profiles'/);
  assert.match(connectorsPage, /query:\s*profileId \? \{ profileId \} : \{\}/);
  assert.match(connectorsPage, /Profile 工作台|Profile workspace/);
});
