import { test } from "node:test";
import assert from "node:assert";
import fs from "node:fs";

const shellSource = fs.readFileSync("apps/web/src/features/workspace/ide-shell/WorkspaceIdeShell.tsx", "utf-8");
const cssSource = fs.readFileSync("apps/web/src/features/workspace/ide-shell/workspace-ide-shell.css", "utf-8");
const pageSource = fs.readFileSync("apps/web/src/features/workspace/WorkspacePage.tsx", "utf-8");
const workspaceIndexSource = fs.readFileSync("apps/web/src/features/workspace/index.ts", "utf-8");
const ideCommandPaletteSource = fs.readFileSync("apps/web/src/features/workspace/ide-shell/IdeCommandPalette.tsx", "utf-8");
const ideCommandsSource = fs.readFileSync("apps/web/src/features/workspace/ide-shell/ideCommands.ts", "utf-8");

test("new Workspace IDE shell has real IDE layout regions", () => {
  assert.match(shellSource, /data-testid="workspace-ide-shell"/);
  assert.match(shellSource, /data-testid="workspace-ide-left-pane"/);
  assert.match(shellSource, /data-testid="workspace-ide-center-pane"/);
  assert.match(shellSource, /data-testid="workspace-ide-right-pane"/);
  assert.match(shellSource, /data-testid="workspace-ide-bottom-pane"/);
  assert.match(shellSource, /IDE activity rail/);
  assert.match(shellSource, /命令、文件、符号、Git、终端、AI 上下文/);
});

test("new Workspace IDE shell models pane/plugin composition", () => {
  for (const token of ["explorer", "search", "git", "terminal", "ai", "extensions", "provider"]) {
    assert.match(shellSource, new RegExp(token));
  }
  assert.match(shellSource, /PANE_REGISTRY/);
  assert.match(shellSource, /DEFAULT_PANE_PLACEMENTS/);
  assert.match(shellSource, /type PanePlacement = "top" \| "left" \| "right" \| "bottom"/);
  assert.match(shellSource, /WorkspaceExplorer/);
  assert.match(shellSource, /WorkspaceSearchPanel/);
  assert.match(shellSource, /WorkspaceGitPanel/);
  assert.match(shellSource, /WorkspaceEditorStage/);
  assert.match(shellSource, /LazyWorkspaceTerminal/);
  assert.match(shellSource, /插件组合/);
});

test("new Workspace IDE shell is responsive for desktop tablet and phone", () => {
  assert.match(cssSource, /grid-template-columns: 72px var\(--ide-left-width\) var\(--ide-resize-width\) minmax\(0, 1fr\) var\(--ide-resize-width\) var\(--ide-right-width\)/);
  assert.match(cssSource, /@media \(max-width: 1100px\)/);
  assert.match(cssSource, /@media \(max-width: 760px\)/);
  assert.match(cssSource, /min-height: 100dvh/);
  assert.match(cssSource, /--ide-bottom-height: min\(42vh, 320px\)/);
  assert.match(cssSource, /grid-template-columns: 1fr/);
  assert.match(cssSource, /grid-template-rows: minmax\(0, 1fr\) 58px/);
  assert.match(cssSource, /scroll-snap-type: x proximity/);
  assert.match(cssSource, /env\(safe-area-inset-bottom\)/);
  assert.match(cssSource, /workspace-ide-shell__editor-grid\[data-ide-editor-split="vertical"\]/);
  assert.match(cssSource, /cursor: row-resize/);
  assert.match(cssSource, /workspace-ide-shell__layout-snapshot/);
});


test("new Workspace IDE shell has explicit mobile panel switching", () => {
  assert.match(shellSource, /type MobilePanel = "editor" \| "top" \| "left" \| "right" \| "bottom"/);
  assert.match(shellSource, /mobilePanel/);
  assert.match(shellSource, /data-ide-mobile-panel=\{mobilePanel\}/);
  assert.match(shellSource, /workspace-ide-shell__mobile-switcher/);
  assert.match(shellSource, /手机工作区面板切换/);
  assert.match(shellSource, /function showMobilePanel\(panel: MobilePanel\)/);
  assert.match(shellSource, /if \(panel === "top"\) setTopOpen\(true\)/);
  assert.match(shellSource, /if \(panel === "left"\) setLeftOpen\(true\)/);
  assert.match(shellSource, /if \(panel === "right"\) setRightOpen\(true\)/);
  assert.match(shellSource, /if \(panel === "bottom"\) setBottomOpen\(true\)/);
  assert.match(shellSource, /setMobilePanel\(panel\)/);
  assert.match(shellSource, /const mobilePanelCommands = React\.useMemo<WorkspaceCommand\[\]>/);
  assert.match(shellSource, /ide\.mobile\.panel\.editor/);
  assert.match(shellSource, /ide\.mobile\.panel\.top/);
  assert.match(shellSource, /ide\.mobile\.panel\.left/);
  assert.match(shellSource, /ide\.mobile\.panel\.right/);
  assert.match(shellSource, /ide\.mobile\.panel\.bottom/);
  assert.match(shellSource, /手机面板：底部终端 Dock/);
  assert.match(shellSource, /\.\.\.mobilePanelCommands/);
  assert.match(shellSource, /onClick=\{\(\) => showMobilePanel\("editor"\)\}/);
  assert.match(shellSource, /onClick=\{\(\) => showMobilePanel\("top"\)\}/);
  assert.match(shellSource, /onClick=\{\(\) => showMobilePanel\("left"\)\}/);
  assert.match(shellSource, /onClick=\{\(\) => showMobilePanel\("right"\)\}/);
  assert.match(shellSource, /onClick=\{\(\) => showMobilePanel\("bottom"\)\}/);
  assert.match(shellSource, /移动面板: \{mobilePanel\}/);
  assert.match(cssSource, /workspace-ide-shell__mobile-switcher/);
  assert.match(cssSource, /workspace-ide-shell\[data-ide-mobile-panel="top"\] \.workspace-ide-shell__center/);
  assert.match(cssSource, /workspace-ide-shell\[data-ide-mobile-panel="left"\] \.workspace-ide-shell__left-pane/);
  assert.match(cssSource, /workspace-ide-shell\[data-ide-mobile-panel="right"\] \.workspace-ide-shell__right-pane/);
  assert.match(cssSource, /workspace-ide-shell\[data-ide-mobile-panel="bottom"\] \.workspace-ide-shell__center/);
  assert.match(cssSource, /workspace-ide-shell\[data-ide-mobile-panel="editor"\] \.workspace-ide-shell__bottom/);
});

test("Workspace uses the new IDE shell as the only native workspace entry", () => {
  assert.match(pageSource, /return <WorkspaceIdeShell \/>/);
  assert.doesNotMatch(pageSource, /WorkspaceWorkbench/);
  assert.doesNotMatch(pageSource, /useWorkspaceLegacyMode/);
  assert.doesNotMatch(pageSource, /legacy/);
});


test("Workspace public API exports the new IDE surface and not the old Workbench", () => {
  assert.match(workspaceIndexSource, /WorkspaceIdeShell/);
  assert.doesNotMatch(workspaceIndexSource, /WorkspaceWorkbench/);
  assert.doesNotMatch(workspaceIndexSource, /\.\/workbench/);
});

test("new Workspace IDE shell owns commands without importing the old workbench", () => {
  assert.match(shellSource, /IdeCommandPalette/);
  assert.match(shellSource, /\.\/ideCommands/);
  assert.doesNotMatch(shellSource, /\.\.\/workbench/);
  assert.match(ideCommandPaletteSource, /new-ide-command-console/);
  assert.match(ideCommandsSource, /WorkspaceCommand/);
});

test("new Workspace IDE shell supports real pane layout controls", () => {
  assert.match(shellSource, /type MaximizedPane/);
  assert.match(shellSource, /type LayoutPreset/);
  assert.match(shellSource, /startPaneResize/);
  assert.match(shellSource, /data-ide-resize-handle=\{pane\}/);
  assert.match(shellSource, /data-ide-layout-preset=\{layoutPreset\}/);
  assert.match(shellSource, /data-ide-maximized-pane=\{maximizedPane/);
  assert.match(shellSource, /applyLayoutPreset\("balanced"\)/);
  assert.match(shellSource, /applyLayoutPreset\("code"\)/);
  assert.match(shellSource, /applyLayoutPreset\("terminal"\)/);
  assert.match(cssSource, /--ide-top-height/);
  assert.match(cssSource, /--ide-left-width/);
  assert.match(cssSource, /--ide-right-width/);
  assert.match(cssSource, /--ide-bottom-height/);
  assert.match(cssSource, /workspace-ide-shell__resize-handle/);
  assert.match(cssSource, /workspace-ide-shell__body--max-center/);
  assert.match(cssSource, /workspace-ide-shell__body--max-bottom/);
});

test("new Workspace IDE shell persists and exposes accessible pane sizing", () => {
  assert.match(shellSource, /IDE_LAYOUT_STORAGE_KEY/);
  assert.match(shellSource, /loadIdeLayoutState/);
  assert.match(shellSource, /storeIdeLayoutState/);
  assert.match(shellSource, /sanitizeIdeLayoutState/);
  assert.match(shellSource, /data-ide-pane-size-state/);
  assert.match(shellSource, /keyboardResizeDelta/);
  assert.match(shellSource, /const key = event\.key\.toLowerCase\(\)/);
  assert.match(shellSource, /if \(event\.key === "Escape"\)/);
  assert.match(shellSource, /if \(draggingPane \|\| dropTarget \|\| edgeDropTarget\)/);
  assert.match(shellSource, /clearPaneDragState\(\)/);
  assert.match(shellSource, /setCommandPaletteOpen\(false\)/);
  assert.match(shellSource, /setMaximizedPane\(null\)/);
  assert.match(shellSource, /key === "\\\\"/);
  assert.match(shellSource, /splitEditor\(event\.shiftKey \? "horizontal" : "vertical"\)/);
  assert.match(shellSource, /key === "b"/);
  assert.match(shellSource, /setLeftOpen\(\(open\) => !open\)/);
  assert.match(shellSource, /key === "j"/);
  assert.match(shellSource, /setBottomOpen\(\(open\) => !open\)/);
  assert.match(shellSource, /if \(!bottomOpen\) setMobilePanel\("bottom"\)/);
  assert.match(shellSource, /ide\.layout\.maximize-left/);
  assert.match(shellSource, /ide\.layout\.maximize-right/);
  assert.match(shellSource, /ide\.layout\.maximize-bottom/);
  assert.match(shellSource, /onKeyDown=\{onKeyDown\}/);
  assert.match(shellSource, /aria-orientation=\{orientation\}/);
  assert.match(shellSource, /aria-valuemin=\{limits\.min\}/);
  assert.match(shellSource, /aria-valuemax=\{limits\.max\}/);
  assert.match(shellSource, /aria-valuenow=\{value\}/);
  assert.match(shellSource, /PANE_SIZE_LIMITS/);
});

test("new Workspace IDE shell supports split editor groups", () => {
  assert.match(shellSource, /type EditorGroupId = "primary" \| "secondary"/);
  assert.match(shellSource, /interface EditorTab/);
  assert.match(shellSource, /type EditorGroupTabs = Record<EditorGroupId, EditorTab\[\]>/);
  assert.match(shellSource, /type EditorSplitMode = "single" \| "vertical" \| "horizontal"/);
  assert.match(shellSource, /editorSplitMode/);
  assert.match(shellSource, /editorSplitRatio/);
  assert.match(shellSource, /data-ide-editor-split=\{editorSplitMode\}/);
  assert.match(shellSource, /data-ide-editor-group=\{group\}/);
  assert.match(shellSource, /editorGroupTabs/);
  assert.match(shellSource, /activeEditorGroup\?: EditorGroupId/);
  assert.match(shellSource, /activePath\?: string/);
  assert.match(shellSource, /activePathRootId\?: string/);
  assert.match(shellSource, /secondaryPath\?: string/);
  assert.match(shellSource, /secondaryPathRootId\?: string/);
  assert.match(shellSource, /editorGroupTabs\?: EditorGroupTabs/);
  assert.match(shellSource, /React\.useState<EditorGroupId>\(layoutState\.activeEditorGroup \?\? "primary"\)/);
  assert.match(shellSource, /React\.useState<string \| undefined>\(layoutState\.activePath\)/);
  assert.match(shellSource, /React\.useState\(layoutState\.activePathRootId \?\? ""\)/);
  assert.match(shellSource, /React\.useState<string \| undefined>\(layoutState\.secondaryPath\)/);
  assert.match(shellSource, /React\.useState\(layoutState\.secondaryPathRootId \?\? ""\)/);
  assert.match(shellSource, /sanitizeEditorGroupTabs\(layoutState\.editorGroupTabs\)/);
  assert.match(shellSource, /const editorSplitMode = isEditorSplitMode\(value\.editorSplitMode\) \? value\.editorSplitMode : undefined/);
  assert.match(shellSource, /const splitEditorActive = editorSplitMode === "vertical" \|\| editorSplitMode === "horizontal"/);
  assert.match(shellSource, /const activeEditorGroup = splitEditorActive && isEditorGroupId\(value\.activeEditorGroup\) \? value\.activeEditorGroup : "primary"/);
  assert.match(shellSource, /activeEditorGroup,/);
  assert.match(shellSource, /activePath: sanitizeLayoutPath\(value\.activePath\)/);
  assert.match(shellSource, /activePathRootId: sanitizeLayoutPath\(value\.activePathRootId\)/);
  assert.match(shellSource, /secondaryPath: splitEditorActive \? sanitizeLayoutPath\(value\.secondaryPath\) : undefined/);
  assert.match(shellSource, /secondaryPathRootId: splitEditorActive \? sanitizeLayoutPath\(value\.secondaryPathRootId\) : undefined/);
  assert.match(shellSource, /editorSplitMode,/);
  assert.match(shellSource, /editorGroupTabs: sanitizeEditorGroupTabs\(value\.editorGroupTabs\)/);
  assert.match(shellSource, /setActivePath\(sanitized\.activePath\)/);
  assert.match(shellSource, /setActivePathRootId\(sanitized\.activePathRootId \?\? ""\)/);
  assert.match(shellSource, /setSecondaryPath\(sanitized\.secondaryPath\)/);
  assert.match(shellSource, /setSecondaryPathRootId\(sanitized\.secondaryPathRootId \?\? ""\)/);
  assert.match(shellSource, /setActiveEditorGroup\(sanitized\.activeEditorGroup \?\? "primary"\)/);
  assert.match(shellSource, /setEditorGroupTabs\(sanitizeEditorGroupTabs\(sanitized\.editorGroupTabs\)\)/);
  assert.match(shellSource, /function sanitizeLayoutPath\(value: unknown\): string \| undefined/);
  assert.match(shellSource, /function isEditorGroupId\(value: unknown\): value is EditorGroupId/);
  assert.match(shellSource, /function sanitizeEditorGroupTabs\(value: unknown\): EditorGroupTabs/);
  assert.match(shellSource, /function sanitizeEditorTabs\(value: unknown\): EditorTab\[\]/);
  assert.match(shellSource, /rememberEditorTab\("primary", path, targetRootId\)/);
  assert.match(shellSource, /rememberEditorTab\("secondary", path, targetRootId\)/);
  assert.match(shellSource, /function rememberEditorTab\(group: EditorGroupId, path: string, tabRootId: string\)/);
  assert.match(shellSource, /upsertEditorTab\(current\[group\], \{ path, rootId: tabRootId \}\)/);
  assert.match(shellSource, /function upsertEditorTab\(tabs: EditorTab\[\], tab: EditorTab\): EditorTab\[\]/);
  assert.match(shellSource, /function mergeEditorTabs\(primaryTabs: EditorTab\[\], secondaryTabs: EditorTab\[\]\): EditorTab\[\]/);
  assert.match(shellSource, /secondaryTabs\.reduce\(\(tabs, tab\) => upsertEditorTab\(tabs, tab\), primaryTabs\)/);
  assert.match(shellSource, /function editorTabLabel\(path: string\)/);
  assert.match(shellSource, /data-ide-editor-tabs=\{group\}/);
  assert.match(shellSource, /data-ide-editor-tab=\{tab\.path\}/);
  assert.match(shellSource, /function focusEditorGroup\(group: EditorGroupId\)/);
  assert.match(shellSource, /setActiveDockFocus\(null\)/);
  assert.match(shellSource, /function activeEditorGroupId\(\): EditorGroupId/);
  assert.match(shellSource, /function activeEditorTab\(\): EditorTab \| null/);
  assert.match(shellSource, /function closeActiveEditorTab\(\)/);
  assert.match(shellSource, /closeEditorTab\(activeEditorGroupId\(\), tab\)/);
  assert.match(shellSource, /id: "ide.editor.close-active-tab"/);
  assert.match(shellSource, /surface: "tab-lifecycle"/);
  assert.match(shellSource, /disabled: !activeEditorTab\(\)/);
  assert.match(shellSource, /run: closeActiveEditorTab/);
  assert.match(shellSource, /id: "ide.editor.next-tab"/);
  assert.match(shellSource, /id: "ide.editor.previous-tab"/);
  assert.match(shellSource, /shortcut: "⌘⌥PageDown"/);
  assert.match(shellSource, /shortcut: "⌘⌥PageUp"/);
  assert.match(shellSource, /disabled: !canNavigateEditorTabs\(\)/);
  assert.match(shellSource, /function canNavigateEditorTabs\(\)/);
  assert.match(shellSource, /function selectAdjacentEditorTab\(direction: "next" \| "previous"\)/);
  assert.match(shellSource, /selectAdjacentEditorTab\("next"\)/);
  assert.match(shellSource, /selectAdjacentEditorTab\("previous"\)/);
  assert.match(shellSource, /event\.key === "PageDown"/);
  assert.match(shellSource, /event\.key === "PageUp"/);
  assert.match(shellSource, /if \(activeDockFocus\) \{/);
  assert.match(shellSource, /hideActiveDockPane\(\);/);
  assert.match(shellSource, /closeActiveEditorTab\(\);/);
  assert.match(shellSource, /shortcut: "Dock 焦点：⌘W"/);
  assert.match(shellSource, /function selectEditorTab\(group: EditorGroupId, tab: EditorTab\)/);
  assert.match(shellSource, /setActivePath\(tab\.path\)/);
  assert.match(shellSource, /setSecondaryPath\(tab\.path\)/);
  assert.match(shellSource, /setActiveEditorGroup\(group\)/);
  assert.match(shellSource, /onSelectTab=\{selectEditorTab\}/);
  assert.match(shellSource, /onCloseTab=\{closeEditorTab\}/);
  assert.match(shellSource, /onBeginTabDrag=\{beginEditorTabDrag\}/);
  assert.match(shellSource, /onDropTabBefore=\{dropEditorTabBefore\}/);
  assert.match(shellSource, /onDropTabAtEnd=\{dropEditorTabAtEnd\}/);
  assert.match(shellSource, /onSelectTab: \(group: EditorGroupId, tab: EditorTab\) => void/);
  assert.match(shellSource, /onCloseTab: \(group: EditorGroupId, tab: EditorTab\) => void/);
  assert.match(shellSource, /function closeEditorTab\(group: EditorGroupId, tab: EditorTab\)/);
  assert.match(shellSource, /currentTabs\.filter\(\(item\) => item\.path !== tab\.path \|\| item\.rootId !== tab\.rootId\)/);
  assert.match(shellSource, /setEditorGroupTabs\(\(current\) => \(\{ \.\.\.current, \[group\]: nextTabs \}\)\)/);
  assert.match(shellSource, /const nextActiveTab = nextTabs\.at\(-1\)/);
  assert.match(shellSource, /setActivePath\(nextActiveTab\?\.path\)/);
  assert.match(shellSource, /setSecondaryPath\(nextActiveTab\?\.path\)/);
  assert.match(shellSource, /data-ide-editor-tab-close=\{tab\.path\}/);
  assert.match(shellSource, /function closeEditorSplit\(\)/);
  assert.match(shellSource, /const fallbackPrimaryTab = activePath \? null : editorGroupTabs\.secondary\.at\(-1\)/);
  assert.match(shellSource, /primary: mergeEditorTabs\(current\.primary, current\.secondary\)/);
  assert.match(shellSource, /secondary: \[\]/);
  assert.match(shellSource, /setSecondaryPath\(undefined\)/);
  assert.match(shellSource, /setSecondaryPathRootId\(""\)/);
  assert.match(shellSource, /focusEditorGroup\("primary"\)/);
  assert.match(shellSource, /function beginEditorTabDrag\(group: EditorGroupId, tab: EditorTab, event: React\.DragEvent\)/);
  assert.match(shellSource, /application\/x-tracevane-editor-tab/);
  assert.match(shellSource, /function reorderEditorTab\(group: EditorGroupId, draggedTab: EditorTab, beforeTab: EditorTab\)/);
  assert.match(shellSource, /function dropEditorTabBefore\(group: EditorGroupId, beforeTab: EditorTab, event: React\.DragEvent\)/);
  assert.match(shellSource, /function dropEditorTabAtEnd\(group: EditorGroupId, event: React\.DragEvent\)/);
  assert.match(shellSource, /parseEditorTabDragPayload\(event\.dataTransfer\.getData\("application\/x-tracevane-editor-tab"\)\)/);
  assert.match(shellSource, /payload\.group === group/);
  assert.match(shellSource, /moveEditorTabToGroup\(payload\.group, group, payload, beforeTab\)/);
  assert.match(shellSource, /function moveEditorTabToGroup\(sourceGroup: EditorGroupId, targetGroup: EditorGroupId, tab: EditorTab, beforeTab: EditorTab\)/);
  assert.match(shellSource, /function moveEditorTabToGroupEnd\(sourceGroup: EditorGroupId, targetGroup: EditorGroupId, tab: EditorTab\)/);
  assert.match(shellSource, /\[sourceGroup\]: current\[sourceGroup\]\.filter/);
  assert.match(shellSource, /\[targetGroup\]: insertEditorTabBefore\(current\[targetGroup\], tab, beforeTab\)/);
  assert.match(shellSource, /\[targetGroup\]: upsertEditorTab\(current\[targetGroup\], tab\)/);
  assert.match(shellSource, /selectEditorTab\(targetGroup, tab\)/);
  assert.match(shellSource, /function reorderEditorTabs\(tabs: EditorTab\[\], draggedTab: EditorTab, beforeTab: EditorTab\): EditorTab\[\]/);
  assert.match(shellSource, /function insertEditorTabBefore\(tabs: EditorTab\[\], draggedTab: EditorTab, beforeTab: EditorTab\): EditorTab\[\]/);
  assert.match(shellSource, /nextTabs\.splice\(targetIndex, 0, draggedTab\)/);
  assert.match(shellSource, /if \(targetIndex < 0\) return upsertEditorTab\(tabs, draggedTab\)/);
  assert.match(shellSource, /function parseEditorTabDragPayload\(value: string\)/);
  assert.match(shellSource, /draggable/);
  assert.match(shellSource, /onDragStart=\{\(event\) => onBeginTabDrag\(group, tab, event\)\}/);
  assert.match(shellSource, /data-ide-editor-tab-drop-zone=\{group\}/);
  assert.match(shellSource, /onDrop=\{\(event\) => onDropTabAtEnd\(group, event\)\}/);
  assert.match(shellSource, /onDrop=\{\(event\) => onDropTabBefore\(group, tab, event\)\}/);
  assert.match(shellSource, /workspace-ide-shell__editor-tab-label/);
  assert.match(shellSource, /workspace-ide-shell__editor-tab-close/);
  assert.match(shellSource, /event\.stopPropagation\(\)/);
  assert.match(shellSource, /onCloseTab\(group, tab\)/);
  assert.match(shellSource, /onClick=\{\(\) => onSelectTab\(group, tab\)\}/);
  assert.match(shellSource, /tabs=\{editorGroupTabs\.primary\}/);
  assert.match(shellSource, /tabs=\{editorGroupTabs\.secondary\}/);
  assert.match(shellSource, /function swapEditorGroups\(\)/);
  assert.match(shellSource, /setEditorGroupTabs\(\(current\) => \(\{ primary: current\.secondary, secondary: current\.primary \}\)\)/);
  assert.match(shellSource, /function moveActiveEditorFileToOtherGroup\(\)/);
  assert.match(shellSource, /const tab = activeEditorTab\(\)/);
  assert.match(shellSource, /const sourceGroup = activeEditorGroupId\(\)/);
  assert.match(shellSource, /const targetGroup: EditorGroupId = sourceGroup === "primary" \? "secondary" : "primary"/);
  assert.match(shellSource, /const nextSourceTabs = current\[sourceGroup\]\.filter/);
  assert.match(shellSource, /\[sourceGroup\]: nextSourceTabs/);
  assert.match(shellSource, /\[targetGroup\]: upsertEditorTab\(current\[targetGroup\], tab\)/);
  assert.match(shellSource, /const fallbackSourceTab = editorGroupTabs\[sourceGroup\]\.filter/);
  assert.match(shellSource, /focusEditorGroup\(targetGroup\)/);
  assert.match(shellSource, /data-ide-editor-split-handle=\{mode\}/);
  assert.match(shellSource, /startEditorSplitResize/);
  assert.match(shellSource, /resizeEditorSplitFromKeyboard/);
  assert.match(shellSource, /ide\.editor\.split-right/);
  assert.match(shellSource, /ide\.editor\.split-down/);
  assert.match(shellSource, /ide\.editor\.close-split/);
  assert.match(shellSource, /function splitEditor\(mode: Exclude<EditorSplitMode, "single">\)/);
  assert.match(shellSource, /const nextSecondaryPath = secondaryPath \?\? activePath/);
  assert.match(shellSource, /const nextSecondaryRootId = secondaryPathRootId \|\| activePathRootId \|\| rootId/);
  assert.match(shellSource, /secondary: upsertEditorTab\(current\.secondary, \{ path: nextSecondaryPath, rootId: nextSecondaryRootId \}\)/);
  assert.match(shellSource, /focusEditorGroup\("secondary"\)/);
  assert.match(shellSource, /ide\.editor\.swap-groups/);
  assert.match(shellSource, /ide\.editor\.move-active-other-group/);
  assert.match(shellSource, /交换主副编辑器组/);
  assert.match(shellSource, /移动当前文件到另一编辑器组/);
  assert.match(shellSource, /shortcut: "⌘⌥S"/);
  assert.match(shellSource, /shortcut: "⌘⌥⇧\]"/);
  assert.match(shellSource, /disabled: !activeEditorTab\(\)/);
  assert.match(shellSource, /run: moveActiveEditorFileToOtherGroup/);
  assert.match(shellSource, /function swapEditorGroups\(\)/);
  assert.match(shellSource, /setEditorGroupTabs\(\(current\) => \(\{ primary: current\.secondary, secondary: current\.primary \}\)\)/);
  assert.match(shellSource, /function moveActiveEditorFileToOtherGroup\(\)/);
  assert.match(shellSource, /const tab = activeEditorTab\(\)/);
  assert.match(shellSource, /if \(!tab\) return/);
  assert.match(shellSource, /const sourceGroup = activeEditorGroupId\(\)/);
  assert.match(shellSource, /const targetGroup: EditorGroupId = sourceGroup === "primary" \? "secondary" : "primary"/);
  assert.match(shellSource, /if \(editorSplitMode === "single"\) \{/);
  assert.match(shellSource, /setEditorSplitMode\("vertical"\)/);
  assert.match(shellSource, /const nextSourceTabs = current\[sourceGroup\]\.filter/);
  assert.match(shellSource, /\[sourceGroup\]: nextSourceTabs/);
  assert.match(shellSource, /\[targetGroup\]: upsertEditorTab\(current\[targetGroup\], tab\)/);
  assert.match(shellSource, /const fallbackSourceTab = editorGroupTabs\[sourceGroup\]\.filter/);
  assert.match(shellSource, /focusEditorGroup\(targetGroup\)/);
  assert.match(shellSource, /event\.shiftKey && event\.key === "\]"/);
  assert.match(shellSource, /moveActiveEditorFileToOtherGroup\(\)/);
  assert.match(shellSource, /disabled: editorSplitMode === "single"/);
  assert.match(shellSource, /run: swapEditorGroups/);
  assert.match(shellSource, /function swapEditorGroups\(\)/);
  assert.match(shellSource, /if \(editorSplitMode === "single"\) return/);
  assert.match(shellSource, /const nextPrimaryPath = secondaryPath \?\? activePath/);
  assert.match(shellSource, /setSecondaryPath\(activePath\)/);
  assert.match(shellSource, /setActivePath\(nextPrimaryPath\)/);
  assert.match(shellSource, /setActiveEditorGroup\(\(group\) => \(group === "primary" \? "secondary" : "primary"\)\)/);
  assert.match(shellSource, /!event\.shiftKey && key === "s"/);
  assert.match(shellSource, /swapEditorGroups\(\)/);
  assert.match(shellSource, /ide\.editor\.focus-primary/);
  assert.match(shellSource, /ide\.editor\.focus-secondary/);
  assert.match(shellSource, /function focusEditorGroup\(group: EditorGroupId\)/);
  assert.match(shellSource, /setActiveDockFocus\(null\)/);
  assert.match(shellSource, /shortcut: "⌘⌥\["/);
  assert.match(shellSource, /shortcut: "⌘⌥\]"/);
  assert.match(shellSource, /event\.key === "\["/);
  assert.match(shellSource, /focusEditorGroup\("primary"\)/);
  assert.match(shellSource, /event\.key === "\]"/);
  assert.match(shellSource, /if \(editorSplitMode === "single"\) splitEditor\("vertical"\)/);
  assert.match(shellSource, /focusEditorGroup\("secondary"\)/);
  assert.match(shellSource, /focusIdeRegion\("center"\)/);
  assert.match(cssSource, /workspace-ide-shell__editor-grid\[data-ide-editor-split="vertical"\]/);
  assert.match(cssSource, /workspace-ide-shell__editor-grid\[data-ide-editor-split="horizontal"\]/);
  assert.match(cssSource, /workspace-ide-shell__editor-split-handle/);
});


test("new Workspace IDE shell supports movable pane registry placements", () => {
  assert.match(shellSource, /type PaneId = "explorer" \| "search" \| "git" \| "terminal" \| "ai" \| "outline" \| "extensions" \| "problems" \| "output"/);
  assert.match(shellSource, /interface PaneDescriptor/);
  assert.match(shellSource, /defaultPlacement: PanePlacement/);
  assert.match(shellSource, /panePlacements/);
  assert.match(shellSource, /groupPanesByPlacement/);
  assert.match(shellSource, /movePaneToPlacement/);
  assert.match(shellSource, /DOCK_PLACEMENTS\.map\(\(placement\) =>/);
  assert.match(shellSource, /ide\.pane\.move\.\$\{pane\.id\}\.\$\{placement\}/);
  assert.match(shellSource, /placementLabel/);
  assert.match(shellSource, /sanitizePanePlacements/);
  assert.match(shellSource, /isPanePlacement/);
  assert.match(shellSource, /窗格: T\{topPaneIds\.length\}\/L\{leftPaneIds\.length\}\/R\{rightPaneIds\.length\}\/B\{bottomPaneIds\.length\}/);
});

test("new Workspace IDE shell exposes direct dock controls for pane movement", () => {
  assert.match(shellSource, /function PaneDockControls/);
  assert.match(shellSource, /data-ide-pane-dock-controls=\{paneId\}/);
  assert.match(shellSource, /placementShortLabel/);
  assert.match(shellSource, /移动 \$\{paneLabel\(paneId\)\} 到\$\{placementLabel\(target\)\}/);
  assert.match(shellSource, /const canAssignToSplitGroup = splitMode && splitMode !== "single"/);
  assert.match(shellSource, /data-ide-pane-assign-primary-group=\{paneId\}/);
  assert.match(shellSource, /data-ide-pane-assign-secondary-group=\{paneId\}/);
  assert.match(shellSource, /把 \$\{paneLabel\(paneId\)\} 放入\$\{placementLabel\(placement\)\} Dock 主窗格组/);
  assert.match(shellSource, /把 \$\{paneLabel\(paneId\)\} 放入\$\{placementLabel\(placement\)\} Dock 副窗格组/);
  assert.match(shellSource, /onMovePane\(paneId, placement, undefined, "primary"\)/);
  assert.match(shellSource, /onMovePane\(paneId, placement, undefined, "secondary"\)/);
  assert.match(shellSource, /disabled=\{!canAssignToSplitGroup\}/);
  assert.match(shellSource, /关闭\$\{placementLabel\(placement\)\} Dock/);
  assert.match(shellSource, /onMovePane\(paneId, target\)/);
  assert.match(shellSource, /onFocusOtherGroup\?: \(\) => void/);
  assert.match(shellSource, /canFocusOtherGroup\?: boolean/);
  assert.match(shellSource, /data-ide-dock-focus-other-group=\{placement\}/);
  assert.match(shellSource, /切换\$\{placementLabel\(placement\)\} Dock 主副窗格组焦点/);
  assert.match(shellSource, /disabled=\{!canFocusOtherGroup\}/);
  assert.match(shellSource, /onClick=\{onFocusOtherGroup\}/);
  assert.match(shellSource, /onCloseDock=\{\(\) => setLeftOpen\(false\)\}/);
  assert.match(shellSource, /onCloseDock=\{\(\) => setRightOpen\(false\)\}/);
  assert.match(shellSource, /onCloseDock=\{\(\) => setBottomOpen\(false\)\}/);
  assert.match(cssSource, /workspace-ide-shell__pane-dock-controls/);
  assert.match(cssSource, /workspace-ide-shell__dock-tab/);
});

test("new Workspace IDE shell treats empty docks as explicit layout states", () => {
  assert.match(shellSource, /function EmptyDockPane/);
  assert.match(shellSource, /data-ide-empty-dock=\{placement\}/);
  assert.match(shellSource, /function resetPanePlacements/);
  assert.match(shellSource, /setPanePlacements\(DEFAULT_PANE_PLACEMENTS\)/);
  assert.match(shellSource, /setDockPaneSelections\(DEFAULT_DOCK_PANE_SELECTIONS\)/);
  assert.match(shellSource, /setHiddenPanes\(\[\]\)/);
  assert.match(shellSource, /setActiveDockFocus\(null\)/);
  assert.match(shellSource, /setMaximizedPane\(null\)/);
  assert.match(shellSource, /setMobilePanel\("editor"\)/);
  assert.match(shellSource, /ide\.pane\.reset-placements/);
  assert.match(shellSource, /activeLeftPane = dockPaneSelection\(leftPaneIds, dockPaneSelections\.left\.primary, activity\)/);
  assert.match(shellSource, /activeRightPane = dockPaneSelection\(rightPaneIds, dockPaneSelections\.right\.primary, rightPanel\)/);
  assert.match(shellSource, /activeBottomPane = dockPaneSelection\(bottomPaneIds, dockPaneSelections\.bottom\.primary, bottomPanel\)/);
  assert.doesNotMatch(shellSource, /leftPaneIds\[0\] \?\? "explorer"/);
  assert.doesNotMatch(shellSource, /rightPaneIds\[0\] \?\? "ai"/);
  assert.doesNotMatch(shellSource, /bottomPaneIds\[0\] \?\? "terminal"/);
  assert.match(cssSource, /workspace-ide-shell__empty-dock/);
});

test("new Workspace IDE shell supports drag and drop pane docking", () => {
  assert.match(shellSource, /draggingPane/);
  assert.match(shellSource, /dropTarget/);
  assert.match(shellSource, /function beginPaneDrag/);
  assert.match(shellSource, /application\/x-tracevane-pane/);
  assert.match(shellSource, /function dragPaneOverDock/);
  assert.match(shellSource, /function dropPaneOnDock/);
  assert.match(shellSource, /function dropPaneOnDockGroup/);
  assert.match(shellSource, /role: DockPaneRole = "primary"/);
  assert.match(shellSource, /movePaneToPlacement\(paneId, placement, beforePaneId, role\)/);
  assert.match(shellSource, /movePaneToPlacement\(paneId, placement, undefined, role\)/);
  assert.match(shellSource, /function leavePaneDock/);
  assert.match(shellSource, /data-ide-dock-placement="top"/);
  assert.match(shellSource, /data-ide-dock-placement="left"/);
  assert.match(shellSource, /data-ide-dock-placement="right"/);
  assert.match(shellSource, /data-ide-dock-placement="bottom"/);
  assert.match(shellSource, /data-ide-pane-draggable=\{paneId\}/);
  assert.match(shellSource, /draggable/);
  assert.match(shellSource, /isPaneId/);
  assert.match(cssSource, /workspace-ide-shell__body--dragging-pane/);
  assert.match(cssSource, /is-drop-target/);
  assert.match(cssSource, /cursor: grab/);
});



test("new Workspace IDE shell supports top dock pane placement", () => {
  assert.match(shellSource, /topOpen/);
  assert.match(shellSource, /topPanel/);
  assert.match(shellSource, /topPaneIds/);
  assert.match(shellSource, /activeTopPane/);
  assert.match(shellSource, /data-testid="workspace-ide-top-pane"/);
  assert.match(shellSource, /data-ide-dock-placement="top"/);
  assert.match(shellSource, /placement="top"/);
  assert.match(shellSource, /setTopOpen\(true\)/);
  assert.match(shellSource, /toggleMaximizedPane\("top"\)/);
  assert.match(shellSource, /ResizeHandle[\s\S]*pane="top"/);
  assert.match(shellSource, /T\{topPaneIds\.length\}/);
  assert.match(cssSource, /--ide-top-height/);
  assert.match(cssSource, /workspace-ide-shell__top-dock/);
  assert.match(cssSource, /workspace-ide-shell__top-tabs/);
  assert.match(cssSource, /workspace-ide-shell__top-tab/);
  assert.match(cssSource, /workspace-ide-shell__body--max-top/);
  assert.match(cssSource, /data-ide-resize-handle="top"/);
});

test("new Workspace IDE shell persists pane order and supports tab reorder drops", () => {
  assert.match(shellSource, /type PaneOrder = Record<PanePlacement, PaneId\[\]>/);
  assert.match(shellSource, /topPaneIds/);
  assert.match(shellSource, /DEFAULT_PANE_ORDER/);
  assert.match(shellSource, /paneOrder/);
  assert.match(shellSource, /setPaneOrder/);
  assert.match(shellSource, /groupPanesByPlacement\(panePlacements, paneOrder, hiddenPanes\)/);
  assert.match(shellSource, /function reorderPane/);
  assert.match(shellSource, /beforePaneId\?: PaneId/);
  assert.match(shellSource, /dropPaneOnDock\("top", event, paneId\)/);
  assert.match(shellSource, /dropPaneOnDock\("left", event, item\.id\)/);
  assert.match(shellSource, /dropPaneOnDock\("bottom", event, paneId\)/);
  assert.match(shellSource, /dropPaneOnDock\("right", event, paneId\)/);
  assert.match(shellSource, /function sanitizePaneOrder/);
  assert.match(shellSource, /function sanitizePaneOrderGroup/);
  assert.match(shellSource, /paneOrder: sanitizePaneOrder\(value\.paneOrder\)/);
  assert.match(shellSource, /顺序: \{topPaneIds\.join\("\|"\)/);
});


test("new Workspace IDE shell supports split dock groups", () => {
  assert.match(shellSource, /type DockSplitMode = "single" \| "vertical" \| "horizontal"/);
  assert.match(shellSource, /type DockSplitModes = Record<PanePlacement, DockSplitMode>/);
  assert.match(shellSource, /type DockSplitRatios = Record<PanePlacement, number>/);
  assert.match(shellSource, /type DockPaneRole = "primary" \| "secondary"/);
  assert.match(shellSource, /type DockDropEdge = "top" \| "right" \| "bottom" \| "left"/);
  assert.match(shellSource, /type DockEdgeDropTarget = \{ placement: PanePlacement; edge: DockDropEdge \} \| null/);
  assert.match(shellSource, /type ActiveDockFocus = \{ placement: PanePlacement; role: DockPaneRole; paneId: PaneId \} \| null/);
  assert.match(shellSource, /type DockPaneSelections = Record<PanePlacement, Partial<Record<DockPaneRole, PaneId>>>/);
  assert.match(shellSource, /const DOCK_PLACEMENTS = \["top", "left", "right", "bottom"\]/);
  assert.match(shellSource, /DEFAULT_DOCK_SPLIT_MODES/);
  assert.match(shellSource, /DEFAULT_DOCK_SPLIT_RATIOS/);
  assert.match(shellSource, /dockSplitModes/);
  assert.match(shellSource, /dockSplitRatios/);
  assert.match(shellSource, /dockPaneSelections/);
  assert.match(shellSource, /activeDockFocus/);
  assert.match(shellSource, /function setDockSplitMode/);
  assert.match(shellSource, /function selectDockPane/);
  assert.match(shellSource, /const oppositeRole: DockPaneRole = role === "primary" \? "secondary" : "primary"/);
  assert.match(shellSource, /if \(nextSelection\[oppositeRole\] === paneId\)/);
  assert.match(shellSource, /const previousRolePane = currentSelection\[role\]/);
  assert.match(shellSource, /secondaryDockPane\(dockPaneIdsForPlacement\(placement\), paneId\)/);
  assert.match(shellSource, /function selectDockTab/);
  assert.match(shellSource, /function setPrimaryDockPanel/);
  assert.match(shellSource, /function focusDockPane/);
  assert.match(shellSource, /function activeDockPaneForPlacement/);
  assert.match(shellSource, /function dockPaneIdsForPlacement/);
  assert.match(shellSource, /function canNavigateActiveDockGroup/);
  assert.match(shellSource, /function canFocusOppositeDockGroup/);
  assert.match(shellSource, /function focusOppositeDockGroup/);
  assert.match(shellSource, /activeDockFocus\.role === "primary" \? "secondary" : "primary"/);
  assert.match(shellSource, /focusDockPane\(activeDockFocus\.placement, nextRole, nextPane\)/);
  assert.match(shellSource, /function canMoveActiveDockPaneToOppositeGroup/);
  assert.match(shellSource, /function moveActiveDockPaneToOppositeGroup/);
  assert.match(shellSource, /movePaneToPlacement\(paneId, activeDockFocus\.placement, undefined, nextRole\)/);
  assert.match(shellSource, /edgeDropTarget/);
  assert.match(shellSource, /data-ide-edge-drop-target=\{edgeDropTarget \? `\$\{edgeDropTarget\.placement\}:\$\{edgeDropTarget\.edge\}` : ""\}/);
  assert.match(shellSource, /function dragPaneOverDockEdge\(placement: PanePlacement, edge: DockDropEdge, event: React\.DragEvent\)/);
  assert.match(shellSource, /setEdgeDropTarget\(\{ placement, edge \}\)/);
  assert.match(shellSource, /function leavePaneDockEdge\(placement: PanePlacement, edge: DockDropEdge, event: React\.DragEvent\)/);
  assert.match(shellSource, /setEdgeDropTarget\(\(current\) => \(current\?\.placement === placement && current\.edge === edge \? null : current\)\)/);
  assert.match(shellSource, /function dropPaneOnDockEdge\(placement: PanePlacement, edge: DockDropEdge, event: React\.DragEvent\)/);
  assert.match(shellSource, /setEdgeDropTarget\(null\)/);
  assert.match(shellSource, /const nextSplitMode: DockSplitMode = edge === "left" \|\| edge === "right" \? "vertical" : "horizontal"/);
  assert.match(shellSource, /const nextRole: DockPaneRole = edge === "right" \|\| edge === "bottom" \? "secondary" : "primary"/);
  assert.match(shellSource, /setDockSplitMode\(placement, nextSplitMode\)/);
  assert.match(shellSource, /movePaneToPlacement\(paneId, placement, undefined, nextRole\)/);
  assert.match(shellSource, /function selectAdjacentDockPane/);
  assert.match(shellSource, /selectDockPane\(activeDockFocus\.placement, activeDockFocus\.role, paneIds\[nextIndex\]\)/);
  assert.match(shellSource, /function canSwapDockSplit/);
  assert.match(shellSource, /function swapDockSplitPanes/);
  assert.match(shellSource, /setPrimaryDockPanel\(placement, secondaryPane\)/);
  assert.match(shellSource, /focusDockPane\(placement, "primary", secondaryPane\)/);
  assert.match(shellSource, /function mergeDockSplitGroups\(placement: PanePlacement, preferredRole: DockPaneRole = "primary"\)/);
  assert.match(shellSource, /const mergedPane = preferredRole === "secondary" \? secondaryPane \?\? primaryPane : primaryPane \?\? secondaryPane/);
  assert.match(shellSource, /setDockSplitMode\(placement, "single"\)/);
  assert.match(shellSource, /secondary: mergedPane === secondaryPane \? primaryPane : secondaryPane/);
  assert.match(shellSource, /focusDockPane\(placement, "primary", mergedPane\)/);
  assert.match(shellSource, /function resetDockSplitRatio/);
  assert.match(shellSource, /function openDockPlacement/);
  assert.match(shellSource, /function closeDockPlacement/);
  assert.match(shellSource, /setActiveDockFocus\(\(current\) => \(current\?\.placement === placement \? null : current\)\)/);
  assert.match(shellSource, /setMaximizedPane\(\(current\) => \(current === placement \? null : current\)\)/);
  assert.match(shellSource, /if \(mobilePanel === placement\) setMobilePanel\("editor"\)/);
  assert.match(shellSource, /function startDockSplitResize/);
  assert.match(shellSource, /function resizeDockSplitFromKeyboard/);
  assert.match(shellSource, /const activeDockGroupCommands = React\.useMemo<WorkspaceCommand\[\]>/);
  assert.match(shellSource, /ide\.pane\.move\.\$\{pane\.id\}\.active-dock-group/);
  assert.match(shellSource, /移动 \$\{pane\.label\} 到当前聚焦窗格组/);
  assert.match(shellSource, /disabled: !activeDockFocus/);
  assert.match(shellSource, /movePaneToPlacement\(pane\.id, activeDockFocus\.placement, undefined, activeDockFocus\.role\)/);
  assert.match(shellSource, /const activeDockLayoutCommands = React\.useMemo<WorkspaceCommand\[\]>/);
  assert.match(shellSource, /ide\.dock\.active\.split-right/);
  assert.match(shellSource, /shortcut: "⌘⌥\\\\"/);
  assert.match(shellSource, /ide\.dock\.active\.split-down/);
  assert.match(shellSource, /shortcut: "⌘⌥⇧\\\\"/);
  assert.match(shellSource, /ide\.dock\.active\.swap-groups/);
  assert.match(shellSource, /ide\.dock\.active\.close-split/);
  assert.match(shellSource, /shortcut: "⌘⌥0"/);
  assert.match(shellSource, /mergeDockSplitGroups\(activeDockFocus\.placement, activeDockFocus\.role\)/);
  assert.match(shellSource, /ide\.dock\.active\.focus-other-group/);
  assert.match(shellSource, /切换当前 Dock 主副窗格组焦点/);
  assert.match(shellSource, /shortcut: "⌘⌥Tab"/);
  assert.match(shellSource, /disabled: !canFocusOppositeDockGroup\(\)/);
  assert.match(shellSource, /run: focusOppositeDockGroup/);
  assert.match(shellSource, /ide\.dock\.active\.move-pane-other-group/);
  assert.match(shellSource, /移动当前 Pane 到另一窗格组/);
  assert.match(shellSource, /shortcut: "⌘⌥⇧Tab"/);
  assert.match(shellSource, /disabled: !canMoveActiveDockPaneToOppositeGroup\(\)/);
  assert.match(shellSource, /run: moveActiveDockPaneToOppositeGroup/);
  assert.match(shellSource, /if \(event\.key === "\\\\"\)/);
  assert.match(shellSource, /setDockSplitMode\(activeDockFocus\.placement, event\.shiftKey \? "horizontal" : "vertical"\)/);
  assert.match(shellSource, /if \(!event\.shiftKey && event\.key === "0"\)/);
  assert.match(shellSource, /if \(activeDockFocus\) mergeDockSplitGroups\(activeDockFocus\.placement, activeDockFocus\.role\)/);
  assert.match(shellSource, /event\.shiftKey && event\.key === "Tab"/);
  assert.match(shellSource, /moveActiveDockPaneToOppositeGroup\(\)/);
  assert.match(shellSource, /event\.key === "Tab"/);
  assert.match(shellSource, /focusOppositeDockGroup\(\)/);
  assert.match(shellSource, /ide\.dock\.active\.next-pane/);
  assert.match(shellSource, /shortcut: "⌘⌥⇧PageDown"/);
  assert.match(shellSource, /ide\.dock\.active\.previous-pane/);
  assert.match(shellSource, /shortcut: "⌘⌥⇧PageUp"/);
  assert.match(shellSource, /ide\.dock\.active\.reset-ratio/);
  assert.match(shellSource, /ide\.dock\.active\.grow/);
  assert.match(shellSource, /ide\.dock\.active\.shrink/);
  assert.match(shellSource, /放大当前 Dock/);
  assert.match(shellSource, /缩小当前 Dock/);
  assert.match(shellSource, /shortcut: "⌘⌥="/);
  assert.match(shellSource, /shortcut: "⌘⌥-"/);
  assert.match(shellSource, /event\.key === "=" \|\| event\.key === "\+"/);
  assert.match(shellSource, /resizeActiveDockPlacement\(KEYBOARD_RESIZE_LARGE_STEP\)/);
  assert.match(shellSource, /event\.key === "-"/);
  assert.match(shellSource, /resizeActiveDockPlacement\(-KEYBOARD_RESIZE_LARGE_STEP\)/);
  assert.match(shellSource, /function resizeActiveDockPlacement\(delta: number\)/);
  assert.match(shellSource, /const pane = activeDockFocus\.placement/);
  assert.match(shellSource, /clamp\(current\[pane\] \+ delta, min, max\)/);
  assert.match(shellSource, /run: \(\) => resizeActiveDockPlacement\(KEYBOARD_RESIZE_LARGE_STEP\)/);
  assert.match(shellSource, /run: \(\) => resizeActiveDockPlacement\(-KEYBOARD_RESIZE_LARGE_STEP\)/);
  assert.match(shellSource, /ide\.dock\.active\.maximize/);
  assert.match(shellSource, /ide\.dock\.active\.collapse/);
  assert.match(shellSource, /shortcut: "⌘⌥M"/);
  assert.match(shellSource, /shortcut: "⌘⌥H"/);
  assert.match(shellSource, /if \(!event\.shiftKey && key === "m"\)/);
  assert.match(shellSource, /openDockPlacement\(activeDockFocus\.placement\)/);
  assert.match(shellSource, /toggleMaximizedPane\(activeDockFocus\.placement\)/);
  assert.match(shellSource, /if \(!event\.shiftKey && key === "h"\)/);
  assert.match(shellSource, /closeDockPlacement\(activeDockFocus\.placement\)/);
  assert.match(shellSource, /disabled: !activeDockFocus \|\| !canSwapDockSplit\(activeDockFocus\.placement\)/);
  assert.match(shellSource, /setDockSplitMode\(activeDockFocus\.placement, "vertical"\)/);
  assert.match(shellSource, /setDockSplitMode\(activeDockFocus\.placement, "horizontal"\)/);
  assert.match(shellSource, /swapDockSplitPanes\(activeDockFocus\.placement\)/);
  assert.match(shellSource, /disabled: !canNavigateActiveDockGroup\(\)/);
  assert.match(shellSource, /if \(event\.shiftKey\) \{\n            selectAdjacentDockPane\("next"\)/);
  assert.match(shellSource, /if \(event\.shiftKey\) \{\n            selectAdjacentDockPane\("previous"\)/);
  assert.match(shellSource, /selectAdjacentDockPane\("next"\)/);
  assert.match(shellSource, /selectAdjacentDockPane\("previous"\)/);
  assert.match(shellSource, /resetDockSplitRatio\(activeDockFocus\.placement\)/);
  assert.match(shellSource, /toggleMaximizedPane\(activeDockFocus\.placement\)/);
  assert.match(shellSource, /closeDockPlacement\(activeDockFocus\.placement\)/);
  assert.match(shellSource, /const dockSplitCommands = React\.useMemo<WorkspaceCommand\[\]>/);
  assert.match(shellSource, /ide\.dock\.split\.\$\{placement\}\.right/);
  assert.match(shellSource, /ide\.dock\.split\.\$\{placement\}\.down/);
  assert.match(shellSource, /ide\.dock\.close-split\.\$\{placement\}/);
  assert.match(shellSource, /ide\.dock\.reset-ratio\.\$\{placement\}/);
  assert.match(shellSource, /ide\.dock\.swap-groups\.\$\{placement\}/);
  assert.match(shellSource, /disabled: !canSwapDockSplit\(placement\)/);
  assert.match(shellSource, /run: \(\) => swapDockSplitPanes\(placement\)/);
  assert.match(shellSource, /run: \(\) => mergeDockSplitGroups\(placement\)/);
  assert.match(shellSource, /\.\.\.activeDockGroupCommands/);
  assert.match(shellSource, /\.\.\.activeDockLayoutCommands/);
  assert.match(shellSource, /\.\.\.dockSplitCommands/);
  assert.match(shellSource, /function DockPaneFrame/);
  assert.match(shellSource, /function DockSplitHandle/);
  assert.match(shellSource, /activeFocus: ActiveDockFocus/);
  assert.match(shellSource, /onFocusPane: \(placement: PanePlacement, role: DockPaneRole, paneId: PaneId\) => void/);
  assert.match(shellSource, /onDropPaneOnGroup: \(placement: PanePlacement, role: DockPaneRole, event: React\.DragEvent\) => void/);
  assert.match(shellSource, /edgeDropTarget: DockEdgeDropTarget/);
  assert.match(shellSource, /onDragPaneOverEdge: \(placement: PanePlacement, edge: DockDropEdge, event: React\.DragEvent\) => void/);
  assert.match(shellSource, /onLeavePaneEdge: \(placement: PanePlacement, edge: DockDropEdge, event: React\.DragEvent\) => void/);
  assert.match(shellSource, /onDropPaneOnEdge: \(placement: PanePlacement, edge: DockDropEdge, event: React\.DragEvent\) => void/);
  assert.match(shellSource, /onDropPaneOnGroup=\{dropPaneOnDockGroup\}/);
  assert.match(shellSource, /edgeDropTarget=\{edgeDropTarget\}/);
  assert.match(shellSource, /onDragPaneOverEdge=\{dragPaneOverDockEdge\}/);
  assert.match(shellSource, /onLeavePaneEdge=\{leavePaneDockEdge\}/);
  assert.match(shellSource, /onDropPaneOnEdge=\{dropPaneOnDockEdge\}/);
  assert.match(shellSource, /onSwapDockGroups=\{swapDockSplitPanes\}/);
  assert.match(shellSource, /onMergeDockGroups=\{mergeDockSplitGroups\}/);
  assert.match(shellSource, /onFocusOtherGroup=\{focusOppositeDockGroup\}/);
  assert.match(shellSource, /canFocusOtherGroup=\{canFocusOppositeDockGroup\(\) && activeDockFocus\?\.placement === "left"\}/);
  assert.match(shellSource, /canFocusOtherGroup=\{canFocusOppositeDockGroup\(\) && activeDockFocus\?\.placement === "top"\}/);
  assert.match(shellSource, /canFocusOtherGroup=\{canFocusOppositeDockGroup\(\) && activeDockFocus\?\.placement === "right"\}/);
  assert.match(shellSource, /canFocusOtherGroup=\{canFocusOppositeDockGroup\(\) && activeDockFocus\?\.placement === "bottom"\}/);
  assert.match(shellSource, /data-ide-dock-swap-groups=\{placement\}/);
  assert.match(shellSource, /data-ide-dock-merge-groups=\{placement\}/);
  assert.match(shellSource, /data-ide-dock-focus-other-group=\{placement\}/);
  assert.match(shellSource, /交换\$\{placementLabel\(placement\)\} Dock 主副窗格组/);
  assert.match(shellSource, /合并\$\{placementLabel\(placement\)\} Dock 主副窗格组/);
  assert.match(shellSource, /切换\$\{placementLabel\(placement\)\} Dock 主副窗格组焦点/);
  assert.match(shellSource, /function DockEdgeDropZones/);
  assert.match(shellSource, /const edges: DockDropEdge\[\] = \["top", "right", "bottom", "left"\]/);
  assert.match(shellSource, /data-ide-dock-edge-drop-zone=\{edge\}/);
  assert.match(shellSource, /data-ide-dock-edge-placement=\{placement\}/);
  assert.match(shellSource, /data-ide-dock-edge-drop-active=\{active \? "true" : "false"\}/);
  assert.match(shellSource, /onDragOver=\{\(event\) => onDragPaneOverEdge\(placement, edge, event\)\}/);
  assert.match(shellSource, /onDragLeave=\{\(event\) => onLeavePaneEdge\(placement, edge, event\)\}/);
  assert.match(shellSource, /onDrop=\{\(event\) => onDropPaneOnEdge\(placement, edge, event\)\}/);
  assert.match(shellSource, /function dockDropEdgeLabel\(edge: DockDropEdge\): string/);
  assert.match(shellSource, /data-ide-dock-split-active=\{isFocused \? "true" : "false"\}/);
  assert.match(shellSource, /data-ide-dock-selection-state=\{dockSelectionState\(dockPaneSelections\)\}/);
  assert.match(cssSource, /workspace-ide-shell__dock-edge-drop-zone/);
  assert.match(cssSource, /pointer-events: none/);
  assert.match(cssSource, /workspace-ide-shell\[data-ide-dragging-pane\]:not\(\[data-ide-dragging-pane=""\]\) \.workspace-ide-shell__dock-edge-drop-zone/);
  assert.match(cssSource, /pointer-events: auto/);
  assert.match(cssSource, /data-ide-dock-edge-drop-active="true"/);
  assert.match(cssSource, /data-ide-dock-edge-drop-zone="top"/);
  assert.match(cssSource, /data-ide-dock-edge-drop-zone="right"/);
  assert.match(cssSource, /data-ide-dock-edge-drop-zone="bottom"/);
  assert.match(cssSource, /data-ide-dock-edge-drop-zone="left"/);
  assert.match(shellSource, /tabIndex=\{0\}/);
  assert.match(shellSource, /workspace-ide-shell__dock-split-pane-badge/);
  assert.match(shellSource, /聚焦窗格: \{activeDockFocus \? `\$\{placementShortLabel\(activeDockFocus\.placement\)\}:\$\{activeDockFocus\.role\}:\$\{activeDockFocus\.paneId\}` : "无"\}/);
  assert.match(shellSource, /secondaryLeftPane/);
  assert.match(shellSource, /dockPaneSelection\(leftPaneIds, dockPaneSelections\.left\.secondary, secondaryDockPane\(leftPaneIds, activeLeftPane\)\)/);
  assert.match(shellSource, /selectDockTab\("left", item\.id\)/);
  assert.match(shellSource, /selectDockTab\("bottom", paneId\)/);
  assert.match(shellSource, /splitMode=\{dockSplitModes\.left\}/);
  assert.match(shellSource, /splitRatio=\{dockSplitRatios\.left\}/);
  assert.match(shellSource, /renderPane=\{\(paneId, role\) =>/);
  assert.match(shellSource, /revealRequest=\{role === "primary" \? explorerRevealRequest : null\}/);
  assert.match(shellSource, /onSearchCommandsChange=\{role === "primary" \? setSearchCommands : ignoreWorkspaceCommands\}/);
  assert.match(shellSource, /data-ide-dock-split=\{shouldSplit \? splitMode : "single"\}/);
  assert.match(shellSource, /data-ide-dock-split-pane=\{role\}/);
  assert.match(shellSource, /event\.dataTransfer\.dropEffect = "move"/);
  assert.match(shellSource, /onDrop=\{\(event\) => onDropPaneOnGroup\(placement, role, event\)\}/);
  assert.match(shellSource, /data-ide-dock-split-handle=\{mode\}/);
  assert.match(shellSource, /--ide-dock-primary-size/);
  assert.match(shellSource, /aria-valuenow=\{Math\.round\(value\)\}/);
  assert.match(shellSource, /function secondaryDockPane/);
  assert.match(shellSource, /function dockPaneSelection/);
  assert.match(shellSource, /function dockSelectionState/);
  assert.match(shellSource, /function mergeDockPaneSelections/);
  assert.match(shellSource, /top: normalizeDockPaneSelection\(\{ \.\.\.DEFAULT_DOCK_PANE_SELECTIONS\.top, \.\.\.value\?\.top \}, defaultPaneIdsForPlacement\("top"\)\)/);
  assert.match(shellSource, /function normalizeDockPaneSelection\(selection: Partial<Record<DockPaneRole, PaneId>>, paneIds: PaneId\[\]\)/);
  assert.match(shellSource, /if \(selection\.primary && selection\.secondary === selection\.primary\)/);
  assert.match(shellSource, /secondary: secondaryDockPane\(paneIds, selection\.primary\)/);
  assert.match(shellSource, /function defaultPaneIdsForPlacement\(placement: PanePlacement\): PaneId\[\]/);
  assert.match(shellSource, /PANE_REGISTRY\.filter\(\(pane\) => pane\.defaultPlacement === placement\)\.map\(\(pane\) => pane\.id\)/);
  assert.match(shellSource, /function sanitizeDockPaneSelections/);
  assert.match(shellSource, /selections\[placement\] = normalizeDockPaneSelection\(nextSelection, defaultPaneIdsForPlacement\(placement\)\)/);
  assert.match(shellSource, /dockPaneSelections: sanitizeDockPaneSelections\(value\.dockPaneSelections\)/);
  assert.match(shellSource, /sanitizeDockSplitModes/);
  assert.match(shellSource, /sanitizeDockSplitRatios/);
  assert.match(shellSource, /isDockSplitMode/);
  assert.match(shellSource, /aria-label=\{`\$\{placementLabel\(placement\)\} Dock 左右拆分`\}/);
  assert.match(shellSource, /aria-label=\{`\$\{placementLabel\(placement\)\} Dock 上下拆分`\}/);
  assert.match(cssSource, /workspace-ide-shell__dock-split/);
  assert.match(cssSource, /data-ide-dock-split="vertical"/);
  assert.match(cssSource, /data-ide-dock-split="horizontal"/);
  assert.match(cssSource, /workspace-ide-shell__dock-split-divider/);
  assert.match(cssSource, /workspace-ide-shell__dock-split-pane/);
  assert.match(cssSource, /data-ide-dock-split-active="true"/);
  assert.match(cssSource, /workspace-ide-shell__dock-split-pane-badge/);
  assert.match(cssSource, /--ide-dock-primary-size/);
  assert.match(cssSource, /data-ide-dock-split-handle="vertical"/);
  assert.match(cssSource, /data-ide-dock-split-handle="horizontal"/);
  assert.match(cssSource, /cursor: col-resize/);
  assert.match(cssSource, /cursor: row-resize/);
});







test("new Workspace IDE shell supports hide and restore pane visibility", () => {
  assert.match(shellSource, /hiddenPanes\?: PaneId\[\]/);
  assert.match(shellSource, /hiddenPanes, setHiddenPanes/);
  assert.match(shellSource, /groupPanesByPlacement\(panePlacements, paneOrder, hiddenPanes\)/);
  assert.match(shellSource, /hiddenPanes,\n\s+\};/);
  assert.match(shellSource, /hiddenPanes: sanitizeHiddenPanes\(value\.hiddenPanes\)/);
  assert.match(shellSource, /function sanitizeHiddenPanes\(value: PaneId\[\] \| undefined\)/);
  assert.match(shellSource, /const paneVisibilityCommands = React\.useMemo<WorkspaceCommand\[\]>/);
  assert.match(shellSource, /ide\.pane\.\$\{hidden \? "show" : "hide"\}\.\$\{pane\.id\}/);
  assert.match(shellSource, /label: `\$\{hidden \? "恢复" : "隐藏"\} \$\{pane\.label\} Pane`/);
  assert.match(shellSource, /run: \(\) => \(hidden \? restorePane\(pane\.id\) : hidePane\(pane\.id\)\)/);
  assert.match(shellSource, /\.\.\.paneVisibilityCommands/);
  assert.match(shellSource, /function hidePane\(paneId: PaneId\)/);
  assert.match(shellSource, /setHiddenPanes\(\(current\) => \(current\.includes\(paneId\) \? current : \[\.\.\.current, paneId\]\)\)/);
  assert.match(shellSource, /function restorePane\(paneId: PaneId\)/);
  assert.match(shellSource, /setHiddenPanes\(\(current\) => current\.filter\(\(hiddenPane\) => hiddenPane !== paneId\)\)/);
  assert.match(shellSource, /movePaneToPlacement\(paneId, panePlacements\[paneId\] \?\? paneDescriptor\(paneId\)\.defaultPlacement\)/);
  assert.match(shellSource, /onHidePane=\{hidePane\}/);
  assert.match(shellSource, /aria-label=\{`隐藏 \$\{paneLabel\(paneId\)\} Pane`\}/);
  assert.match(shellSource, /onClick=\{\(\) => onHidePane\(paneId\)\}/);
  assert.match(shellSource, /const hiddenPaneSet = new Set\(hiddenPanes\)/);
  assert.match(shellSource, /if \(hiddenPaneSet\.has\(pane\.id\)\) return nextGroups/);
  assert.match(shellSource, /sanitizeHiddenPanes/);
  assert.match(shellSource, /ide\.pane\.hide-active/);
  assert.match(shellSource, /ide\.pane\.restore-all-hidden/);
  assert.match(shellSource, /label: "隐藏当前聚焦 Pane"/);
  assert.match(shellSource, /label: "恢复全部隐藏 Pane"/);
  assert.match(shellSource, /shortcut: "⌘W"/);
  assert.match(shellSource, /disabled: !activeDockFocus/);
  assert.match(shellSource, /disabled: hiddenPanes\.length === 0/);
  assert.match(shellSource, /run: hideActiveDockPane/);
  assert.match(shellSource, /run: restoreAllHiddenPanes/);
  assert.match(shellSource, /function hideActiveDockPane\(\)/);
  assert.match(shellSource, /hidePane\(activeDockPaneForPlacement\(activeDockFocus\.placement, activeDockFocus\.role\) \?\? activeDockFocus\.paneId\)/);
  assert.match(shellSource, /function restoreAllHiddenPanes\(\)/);
  assert.match(shellSource, /const panesToRestore = hiddenPanes/);
  assert.match(shellSource, /setHiddenPanes\(\[\]\)/);
  assert.match(shellSource, /for \(const paneId of panesToRestore\)/);
  assert.match(shellSource, /if \(!event\.shiftKey && key === "w"\)/);
  assert.match(shellSource, /hideActiveDockPane\(\)/);
});

test("new Workspace IDE shell can move the focused pane between dock regions", () => {
  assert.match(shellSource, /const activeDockMoveCommands = React\.useMemo<WorkspaceCommand\[\]>/);
  assert.match(shellSource, /ide\.dock\.active\.move-pane\.\$\{placement\}/);
  assert.match(shellSource, /移动当前聚焦 Pane 到\$\{placementLabel\(placement\)\} Dock/);
  assert.match(shellSource, /disabled: !activeDockFocus/);
  assert.match(shellSource, /run: \(\) => moveActiveDockPaneToPlacement\(placement\)/);
  assert.match(shellSource, /function moveActiveDockPaneToPlacement\(placement: PanePlacement\)/);
  assert.match(shellSource, /const paneId = activeDockPaneForPlacement\(activeDockFocus\.placement, activeDockFocus\.role\) \?\? activeDockFocus\.paneId/);
  assert.match(shellSource, /movePaneToPlacement\(paneId, placement\)/);
  assert.match(shellSource, /\.\.\.activeDockMoveCommands/);
  assert.match(shellSource, /event\.shiftKey && event\.key === "ArrowLeft"/);
  assert.match(shellSource, /event\.shiftKey && event\.key === "ArrowRight"/);
  assert.match(shellSource, /event\.shiftKey && event\.key === "ArrowUp"/);
  assert.match(shellSource, /event\.shiftKey && event\.key === "ArrowDown"/);
  assert.match(shellSource, /moveActiveDockPaneToPlacement\("left"\)/);
  assert.match(shellSource, /moveActiveDockPaneToPlacement\("right"\)/);
  assert.match(shellSource, /moveActiveDockPaneToPlacement\("top"\)/);
  assert.match(shellSource, /moveActiveDockPaneToPlacement\("bottom"\)/);
  assert.match(shellSource, /⌘⌥⇧←/);
  assert.match(shellSource, /⌘⌥⇧→/);
  assert.match(shellSource, /⌘⌥⇧↑/);
  assert.match(shellSource, /⌘⌥⇧↓/);
});

test("new Workspace IDE shell supports keyboard focus between IDE regions", () => {
  assert.match(shellSource, /type IdeFocusRegion = "top" \| "left" \| "center" \| "right" \| "bottom"/);
  assert.match(shellSource, /topDockRef/);
  assert.match(shellSource, /leftDockRef/);
  assert.match(shellSource, /centerPaneRef/);
  assert.match(shellSource, /rightDockRef/);
  assert.match(shellSource, /bottomDockRef/);
  assert.match(shellSource, /function focusIdeRegion\(region: IdeFocusRegion\)/);
  assert.match(shellSource, /function focusIdeRegionNode\(region: IdeFocusRegion\)/);
  assert.match(shellSource, /function ideFocusRegionRef\(region: IdeFocusRegion\)/);
  assert.match(shellSource, /requestAnimationFrame/);
  assert.match(shellSource, /focus\(\{ preventScroll: true \}\)/);
  assert.match(shellSource, /const focusRegionCommands = React\.useMemo<WorkspaceCommand\[\]>/);
  assert.match(shellSource, /ide\.focus\.left/);
  assert.match(shellSource, /ide\.focus\.center/);
  assert.match(shellSource, /ide\.focus\.right/);
  assert.match(shellSource, /ide\.focus\.bottom/);
  assert.match(shellSource, /ide\.focus\.top/);
  assert.match(shellSource, /⌘⌥←/);
  assert.match(shellSource, /⌘⌥↵/);
  assert.match(shellSource, /⌘⌥→/);
  assert.match(shellSource, /⌘⌥↓/);
  assert.match(shellSource, /⌘⌥↑/);
  assert.match(shellSource, /mod && event\.altKey/);
  assert.match(shellSource, /event\.key === "ArrowLeft"/);
  assert.match(shellSource, /event\.key === "ArrowRight"/);
  assert.match(shellSource, /event\.key === "ArrowUp"/);
  assert.match(shellSource, /event\.key === "ArrowDown"/);
  assert.match(shellSource, /event\.key === "Enter"/);
  assert.match(shellSource, /focusIdeRegion\("left"\)/);
  assert.match(shellSource, /focusIdeRegion\("center"\)/);
  assert.match(shellSource, /focusIdeRegion\("right"\)/);
  assert.match(shellSource, /focusIdeRegion\("bottom"\)/);
  assert.match(shellSource, /focusIdeRegion\("top"\)/);
  assert.match(shellSource, /\.\.\.focusRegionCommands/);
  assert.match(shellSource, /data-ide-focus-region="left"/);
  assert.match(shellSource, /data-ide-focus-region="center"/);
  assert.match(shellSource, /data-ide-focus-region="right"/);
  assert.match(shellSource, /data-ide-focus-region="bottom"/);
  assert.match(shellSource, /data-ide-focus-region="top"/);
  assert.match(shellSource, /tabIndex=\{-1\}/);
});

test("new Workspace IDE shell supports named local layout snapshots", () => {
  assert.match(shellSource, /IDE_LAYOUT_SNAPSHOTS_STORAGE_KEY/);
  assert.match(shellSource, /interface IdeLayoutSnapshot/);
  assert.match(shellSource, /MAX_LAYOUT_SNAPSHOTS/);
  assert.match(shellSource, /layoutSnapshots/);
  assert.match(shellSource, /function saveLayoutSnapshot/);
  assert.match(shellSource, /function currentIdeLayoutState\(\): IdeLayoutState/);
  assert.match(shellSource, /activeEditorGroup,/);
  assert.match(shellSource, /activePath,/);
  assert.match(shellSource, /activePathRootId,/);
  assert.match(shellSource, /secondaryPath,/);
  assert.match(shellSource, /secondaryPathRootId,/);
  assert.match(shellSource, /function restoreLayoutSnapshot/);
  assert.match(shellSource, /function deleteLayoutSnapshot/);
  assert.match(shellSource, /function applyIdeLayoutState/);
  assert.match(shellSource, /setActiveDockFocus\(null\)/);
  assert.match(shellSource, /setMobilePanel\("editor"\)/);
  assert.match(shellSource, /function loadIdeLayoutSnapshots/);
  assert.match(shellSource, /function storeIdeLayoutSnapshots/);
  assert.match(shellSource, /function sanitizeIdeLayoutSnapshots/);
  assert.match(shellSource, /ide\.layout\.snapshot\.save/);
  assert.match(shellSource, /layoutSnapshotCommands = React\.useMemo<WorkspaceCommand\[\]>/);
  assert.match(shellSource, /\[layoutSnapshots, bottomOpen, dockPaneSelections, dockSplitModes, dockSplitRatios, editorGroupTabs, editorSplitMode, editorSplitRatio, hiddenPanes/);
  assert.match(shellSource, /ide\.layout\.snapshot\.restore\.\$\{snapshot\.id\}/);
  assert.match(shellSource, /ide\.layout\.snapshot\.delete\.\$\{snapshot\.id\}/);
  assert.match(shellSource, /删除布局快照：\$\{snapshot\.name\}/);
  assert.match(shellSource, /run: \(\) => deleteLayoutSnapshot\(snapshot\.id\)/);
  assert.match(shellSource, /data-ide-layout-snapshot-save/);
  assert.match(shellSource, /data-ide-layout-snapshot=\{snapshot\.id\}/);
  assert.match(shellSource, /aria-label=\{`删除布局快照 \$\{snapshot\.name\}`\}/);
  assert.match(shellSource, /快照: \{layoutSnapshots\.length\}/);
  assert.match(cssSource, /workspace-ide-shell__layout-snapshots/);
  assert.match(cssSource, /workspace-ide-shell__layout-snapshot/);
});
