import * as React from "react";
import { ArrowLeft, Bot, ChevronRight, Pencil, Plus, Trash2 } from "lucide-react";
import { toast } from "@/design/ui/sonner";
import { ConfirmDialog } from "@/design/ui/action-dialog";
import { Badge } from "@/design/ui/badge";
import { Button } from "@/design/ui/button";
import { Sheet, SheetBody, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from "@/design/ui/sheet";
import { ErrorState } from "@/shared/states/ErrorState";
import { Skeleton } from "@/shared/states/Skeleton";
import { useChannelsSummaryQuery, useCreateChannelAccountMutation, useCreateChannelMutation, useDeleteChannelAccountMutation, useDeleteChannelMutation, useUpdateChannelAccountMutation, useUpdateChannelMutation } from "@/lib/query/channels";
import type { ChannelAccountInput, ChannelAccountSummary, ChannelCatalogEntry, ChannelFieldDescriptor, ChannelSettingsInput, ChannelSummary } from "../../../../../../../types/channels";
import { PanelHead, RefreshButton, ResponsiveTable, SearchBox, SelectableRow, StatusPill, WorkbenchToolbar, useSelectedKey } from "../components";
import { StatTile } from "../../_shared";

type ChannelDraft = { type: string; enabled: boolean; groupPolicy: string; streaming: string; dmPolicy: string; responsePrefix: string; threadEnabled: boolean; threadIdleHours: string; threadMaxAgeHours: string; threadSpawnSessions: boolean; };
type BotDraft = { id: string; enabled: boolean; dmPolicy: string; groupPolicy: string; streaming: string; responsePrefix: string; fieldValues: Record<string, string>; };
const emptyChannel: ChannelDraft = { type: "", enabled: true, groupPolicy: "open", streaming: "partial", dmPolicy: "open", responsePrefix: "", threadEnabled: false, threadIdleHours: "24", threadMaxAgeHours: "0", threadSpawnSessions: false };
const emptyBot: BotDraft = { id: "default", enabled: true, dmPolicy: "", groupPolicy: "", streaming: "", responsePrefix: "", fieldValues: {} };
const policyOptions = [{ value: "", label: "继承频道" }, { value: "open", label: "开放：允许所有匹配会话" }, { value: "allowlist", label: "白名单：只允许配置对象" }, { value: "disabled", label: "关闭：不处理此类消息" }];
const streamOptions = [{ value: "", label: "继承频道" }, { value: "off", label: "关闭流式" }, { value: "partial", label: "部分流式：边生成边更新" }, { value: "final", label: "仅最终消息" }];
const groupNames: Record<string, string> = { credentials: "凭据", connection: "连接", files: "文件路径", identity: "身份", behavior: "行为", media: "媒体" };
const fieldLabels: Record<string, string> = {
  token: "访问令牌", botToken: "Bot Token", appToken: "App Token", appId: "App ID / 应用 ID", appSecret: "App Secret / 应用密钥", clientSecret: "Client Secret", signingSecret: "签名密钥", verificationToken: "校验 Token", encryptKey: "加密 Key", serviceAccount: "服务账号 JSON", channelAccessToken: "Channel Access Token", channelSecret: "Channel Secret", accessToken: "Access Token", refreshToken: "Refresh Token", privateKey: "私钥", password: "密码",
  apiUrl: "API 地址", wsUrl: "WebSocket 地址", cdnUrl: "CDN 地址", baseUrl: "Base URL", serverUrl: "服务地址", webhookPath: "Webhook 路径", domain: "租户域名", homeserver: "Homeserver", host: "主机", port: "端口", tls: "启用 TLS", proxy: "代理",
  botUid: "Bot UID", userId: "用户 ID", username: "用户名", nick: "昵称", realname: "真实名称", defaultTo: "默认目标", channels: "频道列表", profile: "配置档", account: "账号", cliPath: "CLI 路径", authDir: "认证目录",
  historyLimit: "历史消息条数", dmHistoryLimit: "私聊历史条数", textChunkLimit: "文本分片长度", maxLinesPerMessage: "单条最大行数", mediaMaxMb: "媒体大小上限 MB", pollIntervalMs: "轮询间隔 ms", heartbeatIntervalMs: "心跳间隔 ms", requireMention: "需要 @ 才响应", ignoreMentionAll: "忽略 @所有人", sendReadReceipts: "发送已读回执", responsePrefix: "回复前缀", messagePrefix: "消息前缀",
};
const optionLabels: Record<string, string> = { "": "继承/未设置", off: "关闭", on: "开启", true: "开启", false: "关闭", open: "开放", allowlist: "白名单", disabled: "关闭", partial: "部分流式", final: "仅最终消息", length: "按长度分片", newline: "按换行分片", always: "总是", mentions: "仅被 @ 时", never: "从不", minimal: "最小", extensive: "完整", online: "在线", idle: "空闲", dnd: "勿扰", invisible: "隐身" };
function labelForField(field: ChannelFieldDescriptor): string { return fieldLabels[field.key] ?? field.label; }
function labelForOption(value: string, label: string): string { return optionLabels[value] ?? label; }
function draftFromChannel(channel?: ChannelSummary): ChannelDraft { return channel ? { type: channel.type, enabled: channel.enabled, groupPolicy: channel.groupPolicy ?? "open", streaming: channel.streaming ?? "partial", dmPolicy: channel.dmPolicy ?? "open", responsePrefix: channel.responsePrefix ?? "", threadEnabled: channel.threadBindings?.enabled ?? false, threadIdleHours: String(channel.threadBindings?.idleHours ?? 24), threadMaxAgeHours: String(channel.threadBindings?.maxAgeHours ?? 0), threadSpawnSessions: channel.threadBindings?.spawnSessions ?? false } : emptyChannel; }
function stringFromValue(value: unknown): string { return Array.isArray(value) ? value.join("\n") : value == null ? "" : String(value); }
function draftFromBot(account?: ChannelAccountSummary, catalog?: ChannelCatalogEntry): BotDraft { const fields = [...(catalog?.accountFields ?? []), ...(catalog?.credentialFields ?? [])]; return { id: account?.id ?? "default", enabled: account?.enabled ?? true, dmPolicy: account?.dmPolicy ?? "", groupPolicy: account?.groupPolicy ?? "", streaming: account?.streaming ?? "", responsePrefix: account?.responsePrefix ?? "", fieldValues: Object.fromEntries(fields.map((field) => [field.key, stringFromValue(account?.fieldValues[field.key])])) }; }
function normalizeFieldValue(field: ChannelFieldDescriptor, value: string): unknown { if (!value.trim()) return undefined; if (field.input === "boolean") return value === "true"; if (field.input === "number") return Number(value); if (field.input === "stringList") return value.split(/\n|,/).map((item) => item.trim()).filter(Boolean); return value; }
function TextInput({ label, value, onChange, disabled = false, placeholder, type = "text" }: { label: string; value: string; onChange: (value: string) => void; disabled?: boolean; placeholder?: string; type?: string }) { return <label className="grid gap-1.5"><span className="text-xs font-medium text-muted">{label}</span><input type={type} disabled={disabled} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="min-w-0 rounded-sm border border-line bg-panel-2 px-3 py-2 text-sm text-ink-strong outline-none focus:shadow-[var(--ring)] disabled:opacity-60" /></label>; }
function SelectInput({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }> }) { return <label className="grid gap-1.5"><span className="text-xs font-medium text-muted">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="min-w-0 rounded-sm border border-line bg-panel-2 px-3 py-2 text-sm text-ink-strong outline-none focus:shadow-[var(--ring)]">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function ToggleInput({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between gap-3 rounded-sm border border-line bg-panel-2 px-3 py-2 text-sm"><span className="font-medium text-ink-strong">{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-primary" /></label>; }
function DynamicField({ field, value, onChange }: { field: ChannelFieldDescriptor; value: string; onChange: (value: string) => void }) { const label = labelForField(field); if (field.input === "boolean") return <SelectInput label={label} value={value} onChange={onChange} options={[{ value: "", label: "继承/未设置" }, { value: "true", label: "开启" }, { value: "false", label: "关闭" }]} />; if (field.input === "select") return <SelectInput label={label} value={value} onChange={onChange} options={(field.options ?? []).map((o) => ({ value: o.value, label: labelForOption(o.value, o.label) }))} />; if (field.input === "textarea" || field.input === "stringList") return <label className="grid gap-1.5 sm:col-span-2"><span className="text-xs font-medium text-muted">{label}</span><textarea value={value} placeholder={field.placeholder} rows={3} onChange={(event) => onChange(event.target.value)} className="min-w-0 resize-y rounded-sm border border-line bg-panel-2 px-3 py-2 text-sm text-ink-strong outline-none focus:shadow-[var(--ring)]" />{field.helpText ? <span className="text-xs text-subtle">{field.helpText}</span> : null}</label>; return <TextInput label={label} type={field.input === "number" ? "number" : field.secret ? "password" : "text"} value={value} placeholder={field.placeholder} onChange={onChange} />; }
function FieldGroups({ fields, draft, setDraft }: { fields: ChannelFieldDescriptor[]; draft: BotDraft; setDraft: React.Dispatch<React.SetStateAction<BotDraft>> }) { const groups = new Map<string, ChannelFieldDescriptor[]>(); for (const field of fields) { const group = field.group ?? (field.secret ? "credentials" : "behavior"); groups.set(group, [...(groups.get(group) ?? []), field]); } return <>{[...groups.entries()].map(([group, groupFields]) => <div key={group} className="grid gap-3"><PanelHead title={groupNames[group] ?? group} sub="字段来自 OpenClaw channel catalog / manifest；不同频道显示不同字段。" /><div className="grid gap-3 sm:grid-cols-2">{groupFields.map((field) => <DynamicField key={field.key} field={field} value={draft.fieldValues[field.key] ?? ""} onChange={(value) => setDraft((prev) => ({ ...prev, fieldValues: { ...prev.fieldValues, [field.key]: value } }))} />)}</div></div>)}</>; }

export function ChannelsPage() {
  const channels = useChannelsSummaryQuery();
  const createChannel = useCreateChannelMutation();
  const updateChannel = useUpdateChannelMutation();
  const deleteChannel = useDeleteChannelMutation();
  const createBot = useCreateChannelAccountMutation();
  const updateBot = useUpdateChannelAccountMutation();
  const deleteBot = useDeleteChannelAccountMutation();
  const [query, setQuery] = React.useState("");
  const [activeType, setActiveType] = React.useState<string | null>(null);
  const [channelEditorOpen, setChannelEditorOpen] = React.useState(false);
  const [botEditorOpen, setBotEditorOpen] = React.useState(false);
  const [channelMode, setChannelMode] = React.useState<"edit" | "new">("edit");
  const [botMode, setBotMode] = React.useState<"edit" | "new">("edit");
  const [channelDraft, setChannelDraft] = React.useState<ChannelDraft>(emptyChannel);
  const [botDraft, setBotDraft] = React.useState<BotDraft>(emptyBot);
  const [deleteTarget, setDeleteTarget] = React.useState<
    | { kind: "channel"; channel: ChannelSummary }
    | { kind: "bot"; channelType: string; bot: ChannelAccountSummary }
    | null
  >(null);
  const list = channels.data?.channels ?? [];
  const filtered = list.filter((channel) => `${channel.type} ${channel.dmPolicy ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const [selectedKey, setSelectedKey] = useSelectedKey(filtered.map((channel) => channel.type));
  const active = list.find((channel) => channel.type === activeType) ?? null;
  const selected = active ?? filtered.find((channel) => channel.type === selectedKey) ?? filtered[0] ?? list[0];
  const selectedCatalog = channels.data?.catalog.find((entry) => entry.type === selected?.type);
  const selectedBots = selected?.accounts ?? [];
  const [selectedBotId, setSelectedBotId] = useSelectedKey(selectedBots.map((bot) => bot.id));
  const selectedBot = selectedBots.find((bot) => bot.id === selectedBotId) ?? selectedBots[0];
  if (channels.isLoading) return <div className="grid gap-[18px]" role="status" aria-busy="true"><Skeleton className="h-[118px] w-full" /><Skeleton className="h-[260px] w-full" /></div>;
  if (channels.error) return <ErrorState title="无法加载 OpenClaw 原生 Channel" description={channels.error.message} />;
  const channelPayload = (): ChannelSettingsInput => ({ enabled: channelDraft.enabled, groupPolicy: channelDraft.groupPolicy, streaming: channelDraft.streaming, dmPolicy: channelDraft.dmPolicy, responsePrefix: channelDraft.responsePrefix, threadBindings: { enabled: channelDraft.threadEnabled, idleHours: Number(channelDraft.threadIdleHours) || 24, maxAgeHours: Number(channelDraft.threadMaxAgeHours) || 0, spawnSessions: channelDraft.threadSpawnSessions } });
  const botPayload = (): ChannelAccountInput => { const fields = [...(selectedCatalog?.accountFields ?? []), ...(selectedCatalog?.credentialFields ?? [])]; const fieldValues: Record<string, unknown> = {}; for (const field of fields) { const value = normalizeFieldValue(field, botDraft.fieldValues[field.key] ?? ""); if (value !== undefined) fieldValues[field.key] = value; } return { id: botDraft.id.trim(), enabled: botDraft.enabled, dmPolicy: botDraft.dmPolicy || null, groupPolicy: botDraft.groupPolicy || null, streaming: botDraft.streaming || null, responsePrefix: botDraft.responsePrefix || null, fieldValues }; };
  const openChannelEditor = (mode: "edit" | "new", channel?: ChannelSummary) => { setChannelMode(mode); setChannelDraft(mode === "new" ? { ...emptyChannel, type: channels.data?.catalog[0]?.type ?? "" } : draftFromChannel(channel)); setChannelEditorOpen(true); };
  const openBotEditor = (mode: "edit" | "new", bot?: ChannelAccountSummary) => { if (!selected) return toast.error("请先进入 Channel"); setBotMode(mode); setBotDraft(mode === "new" ? draftFromBot(undefined, selectedCatalog) : draftFromBot(bot, selectedCatalog)); setBotEditorOpen(true); };
  const saveChannel = () => { if (!channelDraft.type.trim()) return toast.error("Channel 类型不能为空"); if (channelMode === "new") createChannel.mutate({ type: channelDraft.type.trim(), enabled: channelDraft.enabled }, { onSuccess: () => { updateChannel.mutate({ type: channelDraft.type.trim(), payload: channelPayload() }); toast.success("OpenClaw Channel 已新增"); setSelectedKey(channelDraft.type.trim()); setActiveType(channelDraft.type.trim()); setChannelEditorOpen(false); }, onError: (error) => toast.error("新增失败", { description: error.message }) }); else updateChannel.mutate({ type: channelDraft.type, payload: channelPayload() }, { onSuccess: () => { toast.success("OpenClaw Channel 已保存"); setChannelEditorOpen(false); }, onError: (error) => toast.error("保存失败", { description: error.message }) }); };
  const saveBot = () => { if (!selected || !botDraft.id.trim()) return toast.error("Bot ID 不能为空"); if (botMode === "new") createBot.mutate({ type: selected.type, payload: botPayload() }, { onSuccess: () => { toast.success("Bot 已新增"); setSelectedBotId(botDraft.id.trim()); setBotEditorOpen(false); }, onError: (error) => toast.error("新增失败", { description: error.message }) }); else updateBot.mutate({ type: selected.type, accountId: botDraft.id, payload: botPayload() }, { onSuccess: () => { toast.success("Bot 已保存"); setBotEditorOpen(false); }, onError: (error) => toast.error("保存失败", { description: error.message }) }); };
  const removeChannel = (channel: ChannelSummary) => setDeleteTarget({ kind: "channel", channel });
  const removeBot = (bot: ChannelAccountSummary) => {
    if (!selected) return;
    setDeleteTarget({ kind: "bot", channelType: selected.type, bot });
  };
  const catalogOptions = (channels.data?.catalog ?? []).map((entry) => ({ value: entry.type, label: `${entry.icon} ${entry.label} (${entry.type})` }));
  const botFields = [...(selectedCatalog?.accountFields ?? []), ...(selectedCatalog?.credentialFields ?? [])];
  const deleteDialog = <ConfirmDialog open={Boolean(deleteTarget)} title={deleteTarget?.kind === "channel" ? "删除 OpenClaw Channel" : "删除 Bot"} description={deleteTarget?.kind === "channel" ? `删除 ${deleteTarget.channel.type}，相关 Bot 和绑定也会移除。` : deleteTarget?.kind === "bot" ? `删除 ${deleteTarget.channelType}/${deleteTarget.bot.id}，相关绑定可能失效。` : undefined} icon={<Trash2 />} tone="danger" confirmLabel="删除" contentDataAttr="openclaw-channel-delete" onCancel={() => setDeleteTarget(null)} onConfirm={() => { if (!deleteTarget) return; const target = deleteTarget; setDeleteTarget(null); if (target.kind === "channel") deleteChannel.mutate(target.channel.type, { onSuccess: () => { toast.success("OpenClaw Channel 已删除"); setActiveType(null); }, onError: (error) => toast.error("删除失败", { description: error.message }) }); else deleteBot.mutate({ type: target.channelType, accountId: target.bot.id }, { onSuccess: () => toast.success("Bot 已删除"), onError: (error) => toast.error("删除失败", { description: error.message }) }); }} />;
  const editors = <>
    <Sheet open={channelEditorOpen} onOpenChange={setChannelEditorOpen}><SheetContent className="w-[min(620px,94vw)]"><SheetHeader><div><SheetTitle>{channelMode === "new" ? "新增 Channel" : `编辑 ${channelDraft.type}`}</SheetTitle><SheetDescription>Channel 是平台类型；Bot/Account 在频道子页面管理。</SheetDescription></div></SheetHeader><SheetBody><div className="grid gap-3 sm:grid-cols-2"><SelectInput label="Channel 类型" value={channelDraft.type} onChange={(type) => setChannelDraft((p) => ({ ...p, type }))} options={catalogOptions} /><ToggleInput label="启用 Channel" checked={channelDraft.enabled} onChange={(enabled) => setChannelDraft((p) => ({ ...p, enabled }))} /><SelectInput label="群组策略" value={channelDraft.groupPolicy} onChange={(groupPolicy) => setChannelDraft((p) => ({ ...p, groupPolicy }))} options={policyOptions.filter((o) => o.value)} /><SelectInput label="私聊策略" value={channelDraft.dmPolicy} onChange={(dmPolicy) => setChannelDraft((p) => ({ ...p, dmPolicy }))} options={policyOptions.filter((o) => o.value)} /><SelectInput label="流式推送" value={channelDraft.streaming} onChange={(streaming) => setChannelDraft((p) => ({ ...p, streaming }))} options={streamOptions.filter((o) => o.value)} /><TextInput label="回复前缀" value={channelDraft.responsePrefix} onChange={(responsePrefix) => setChannelDraft((p) => ({ ...p, responsePrefix }))} /><ToggleInput label="启用线程绑定" checked={channelDraft.threadEnabled} onChange={(threadEnabled) => setChannelDraft((p) => ({ ...p, threadEnabled }))} /><ToggleInput label="线程自动生成会话" checked={channelDraft.threadSpawnSessions} onChange={(threadSpawnSessions) => setChannelDraft((p) => ({ ...p, threadSpawnSessions }))} /><TextInput label="线程空闲小时" type="number" value={channelDraft.threadIdleHours} onChange={(threadIdleHours) => setChannelDraft((p) => ({ ...p, threadIdleHours }))} /><TextInput label="线程最大保留小时" type="number" value={channelDraft.threadMaxAgeHours} onChange={(threadMaxAgeHours) => setChannelDraft((p) => ({ ...p, threadMaxAgeHours }))} /></div></SheetBody><SheetFooter><Button onClick={saveChannel} disabled={createChannel.isPending || updateChannel.isPending}>{channelMode === "new" ? "新增" : "保存"}</Button><Button variant="outline" onClick={() => setChannelEditorOpen(false)}>取消</Button></SheetFooter></SheetContent></Sheet>
      <Sheet open={botEditorOpen} onOpenChange={setBotEditorOpen}><SheetContent className="w-[min(760px,94vw)]"><SheetHeader><div><SheetTitle>{botMode === "new" ? "新增 Bot" : `编辑 Bot ${botDraft.id}`}</SheetTitle><SheetDescription>{selectedCatalog?.label ?? selected?.type} 的账号实例；字段按该频道 catalog 动态生成，密钥留空不覆盖。</SheetDescription></div></SheetHeader><SheetBody><PanelHead title="Bot 基础与策略" sub="命名 Bot 可创建多个；不支持命名账号的平台只能使用 default。" /><div className="grid gap-3 sm:grid-cols-2"><TextInput label="Bot / Account ID" value={botDraft.id} onChange={(id) => setBotDraft((p) => ({ ...p, id }))} disabled={botMode === "edit"} /><ToggleInput label="启用 Bot" checked={botDraft.enabled} onChange={(enabled) => setBotDraft((p) => ({ ...p, enabled }))} /><SelectInput label="私聊策略" value={botDraft.dmPolicy} onChange={(dmPolicy) => setBotDraft((p) => ({ ...p, dmPolicy }))} options={policyOptions} /><SelectInput label="群组策略" value={botDraft.groupPolicy} onChange={(groupPolicy) => setBotDraft((p) => ({ ...p, groupPolicy }))} options={policyOptions} /><SelectInput label="流式推送" value={botDraft.streaming} onChange={(streaming) => setBotDraft((p) => ({ ...p, streaming }))} options={streamOptions} /><TextInput label="回复前缀" value={botDraft.responsePrefix} onChange={(responsePrefix) => setBotDraft((p) => ({ ...p, responsePrefix }))} /></div>{botFields.length ? <FieldGroups fields={botFields} draft={botDraft} setDraft={setBotDraft} /> : <div className="rounded-sm border border-dashed border-line p-4 text-sm text-muted">该频道没有暴露额外 Bot 字段。</div>}</SheetBody><SheetFooter><Button onClick={saveBot} disabled={createBot.isPending || updateBot.isPending}>{botMode === "new" ? "新增" : "保存"}</Button><Button variant="outline" onClick={() => setBotEditorOpen(false)}>取消</Button></SheetFooter></SheetContent></Sheet>

  </>;
  if (active) return <div className="grid gap-[18px]"><section className="rounded-md border border-line bg-panel shadow-sm"><WorkbenchToolbar title={`${selectedCatalog?.icon ?? "◈"} ${selectedCatalog?.label ?? active.type}`} description="频道子页面：管理此 Channel 下的 Bot/Account；不同频道的表单字段来自 OpenClaw catalog、manifest 和后端映射。"><Button variant="outline" size="sm" onClick={() => setActiveType(null)}><ArrowLeft className="size-4" />返回频道列表</Button><Button size="sm" onClick={() => openBotEditor("new")}><Bot className="size-4" />新增 Bot</Button><Button variant="outline" size="sm" onClick={() => openChannelEditor("edit", active)}><Pencil className="size-4" />编辑 Channel</Button><RefreshButton loading={channels.isFetching} onClick={() => { void channels.refetch(); }} /></WorkbenchToolbar><div className="grid gap-3 p-3"><div className="grid gap-3 md:grid-cols-4"><StatTile label="Bot" value={active.accountCount} sub="账号实例" /><StatTile label="绑定" value={active.bindingCount} sub="Bot → Agent" /><StatTile label="命名 Bot" value={selectedCatalog?.supportsNamedAccounts ? "支持" : "不支持"} sub="catalog" /><StatTile label="字段" value={botFields.length} sub="动态表单字段" /></div><ResponsiveTable columns={["Bot / Account", "凭据", "策略", "状态", "操作"]} rows={selectedBots.map((bot) => <SelectableRow key={bot.id} id={bot.id} selected={selectedBotId === bot.id} onSelect={setSelectedBotId}><td className="px-4 py-3"><div className="font-medium text-ink-strong">{bot.id}</div><div className="text-xs text-muted">{bot.kind === "default" ? "默认 Bot" : "命名 Bot"}</div></td><td className="px-4 py-3 text-muted">{bot.credentialStates.filter((item) => item.configured).length}/{bot.credentialStates.length}</td><td className="px-4 py-3 text-muted">DM {bot.dmPolicy ?? active.dmPolicy ?? "继承"} · 群 {bot.groupPolicy ?? active.groupPolicy ?? "继承"}</td><td className="px-4 py-3"><StatusPill tone={bot.enabled ? "ok" : "warn"}>{bot.enabled ? "启用" : "停用"}</StatusPill></td><td className="px-4 py-3"><div className="flex gap-2"><Button variant="outline" size="sm" onClick={(event) => { event.stopPropagation(); openBotEditor("edit", bot); }}><Pencil className="size-4" />编辑</Button><Button variant="ghost" size="sm" onClick={(event) => { event.stopPropagation(); removeBot(bot); }}><Trash2 className="size-4" />删除</Button></div></td></SelectableRow>)} empty="当前 Channel 还没有 Bot" /></div></section>{selectedBot ? <section className="rounded-md border border-line bg-panel shadow-sm"><PanelHead title={`当前 Bot：${selectedBot.id}`} sub="这里仅展示摘要；完整编辑在抽屉中完成，避免长列表页面被表单拉长。" /><div className="grid gap-3 p-3 md:grid-cols-3"><StatTile label="凭据已配置" value={selectedBot.credentialStates.filter((item) => item.configured).length} sub={`${selectedBot.credentialStates.length} 个字段`} /><StatTile label="私聊策略" value={selectedBot.dmPolicy ?? active.dmPolicy ?? "继承"} sub="DM policy" /><StatTile label="群组策略" value={selectedBot.groupPolicy ?? active.groupPolicy ?? "继承"} sub="Group policy" /></div></section> : null}{editors}{deleteDialog}</div>;
  return <div className="grid gap-[18px]"><section className="rounded-md border border-line bg-panel shadow-sm"><WorkbenchToolbar title="OpenClaw 原生接入：Channel / Bot" description="先选择频道进入子页面，再管理该频道下的多个 Bot。这里不再使用左右分栏。"><SearchBox value={query} onChange={setQuery} placeholder="搜索 Channel" /><Button size="sm" onClick={() => openChannelEditor("new")}><Plus className="size-4" />新增 Channel</Button><RefreshButton loading={channels.isFetching} onClick={() => { void channels.refetch(); }} /><Badge variant="info">可编辑</Badge></WorkbenchToolbar><div className="grid gap-3 p-3"><div className="grid gap-3 md:grid-cols-4"><StatTile label="Channel" value={channels.data?.counts.channels ?? 0} sub="平台类型" /><StatTile label="Bot" value={channels.data?.counts.accounts ?? 0} sub="账号实例" /><StatTile label="绑定" value={channels.data?.counts.bindings ?? 0} sub="Bot → Agent" /><StatTile label="Catalog" value={channels.data?.catalog.length ?? 0} sub="可新增平台" /></div><ResponsiveTable columns={["Channel", "Bot 数", "绑定数", "状态", "操作"]} rows={filtered.map((channel) => <SelectableRow key={channel.type} id={channel.type} selected={selectedKey === channel.type} onSelect={setSelectedKey}><td className="max-w-[300px] truncate px-4 py-3"><div className="font-medium text-ink-strong">{channels.data?.catalog.find((entry) => entry.type === channel.type)?.label ?? channel.type}</div><div className="text-xs text-muted">{channel.type}</div></td><td className="px-4 py-3 text-muted">{channel.accountCount}</td><td className="px-4 py-3 text-muted">{channel.bindingCount}</td><td className="px-4 py-3"><StatusPill tone={channel.enabled ? "ok" : "warn"}>{channel.enabled ? "已启用" : "已停用"}</StatusPill></td><td className="px-4 py-3"><div className="flex gap-2"><Button variant="outline" size="sm" onClick={(event) => { event.stopPropagation(); setActiveType(channel.type); }}><ChevronRight className="size-4" />进入</Button><Button variant="ghost" size="sm" onClick={(event) => { event.stopPropagation(); removeChannel(channel); }}><Trash2 className="size-4" />删除</Button></div></td></SelectableRow>)} empty="无匹配 OpenClaw Channel" /></div></section>
    {editors}
    {deleteDialog}
  </div>;
}
