import * as React from "react";
import { toast } from "@/design/ui/sonner";
import { Button } from "@/design/ui/button";
import { ErrorState } from "@/shared/states/ErrorState";
import { Skeleton } from "@/shared/states/Skeleton";
import { useChannelsSummaryQuery, useCreateChannelMutation, useDeleteChannelMutation, useUpdateChannelMutation } from "@/lib/query/channels";
import { BoundaryBadge, DetailRail, EvidenceRow, PanelHead, RefreshButton, ResponsiveTable, SearchBox, SelectableRow, StatusPill, WorkbenchToolbar, useSelectedKey } from "../components";
import { StatTile } from "../../_shared";

interface ChannelDraft { type: string; enabled: boolean; groupPolicy: string; streaming: string; dmPolicy: string; responsePrefix: string; threadEnabled: boolean; threadIdleHours: string; threadMaxAgeHours: string; threadSpawnSessions: boolean; }
const emptyDraft: ChannelDraft = { type: "", enabled: true, groupPolicy: "open", streaming: "partial", dmPolicy: "open", responsePrefix: "", threadEnabled: false, threadIdleHours: "24", threadMaxAgeHours: "0", threadSpawnSessions: false };

function draftFromChannel(channel: ReturnType<typeof useChannelsSummaryQuery>["data"] extends infer T ? T extends { channels: Array<infer C> } ? C : never : never | undefined): ChannelDraft {
  return channel ? { type: channel.type, enabled: channel.enabled, groupPolicy: channel.groupPolicy ?? "open", streaming: channel.streaming ?? "partial", dmPolicy: channel.dmPolicy ?? "open", responsePrefix: channel.responsePrefix ?? "", threadEnabled: channel.threadBindings?.enabled ?? false, threadIdleHours: String(channel.threadBindings?.idleHours ?? 24), threadMaxAgeHours: String(channel.threadBindings?.maxAgeHours ?? 0), threadSpawnSessions: channel.threadBindings?.spawnSessions ?? false } : emptyDraft;
}
function TextInput({ label, value, onChange, disabled = false, type = "text" }: { label: string; value: string; onChange: (value: string) => void; disabled?: boolean; type?: string }) { return <label className="grid gap-1.5"><span className="text-xs font-medium text-muted">{label}</span><input type={type} disabled={disabled} value={value} onChange={(event) => onChange(event.target.value)} className="min-w-0 rounded-sm border border-line bg-panel-2 px-3 py-2 text-sm text-ink-strong outline-none focus:shadow-[var(--ring)] disabled:opacity-60" /></label>; }
function SelectInput({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <label className="grid gap-1.5"><span className="text-xs font-medium text-muted">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="min-w-0 rounded-sm border border-line bg-panel-2 px-3 py-2 text-sm text-ink-strong outline-none focus:shadow-[var(--ring)]">{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
function ToggleInput({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <label className="flex items-center justify-between gap-3 rounded-sm border border-line bg-panel-2 px-3 py-2 text-sm"><span className="font-medium text-ink-strong">{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-primary" /></label>; }

export function ChannelsPage() {
  const channels = useChannelsSummaryQuery();
  const createChannel = useCreateChannelMutation();
  const updateChannel = useUpdateChannelMutation();
  const deleteChannel = useDeleteChannelMutation();
  const [query, setQuery] = React.useState("");
  const [mode, setMode] = React.useState<"edit" | "new">("edit");
  const list = channels.data?.channels ?? [];
  const filtered = list.filter((channel) => `${channel.type} ${channel.dmPolicy ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const [selectedKey, setSelectedKey] = useSelectedKey(filtered.map((channel) => channel.type));
  const selected = filtered.find((channel) => channel.type === selectedKey) ?? filtered[0] ?? list[0];
  const [draft, setDraft] = React.useState<ChannelDraft>(emptyDraft);
  React.useEffect(() => { if (mode === "edit") setDraft(draftFromChannel(selected)); }, [selected?.type, mode]);
  if (channels.isLoading) return <div className="grid gap-[18px]" role="status" aria-busy="true"><Skeleton className="h-[118px] w-full" /><Skeleton className="h-[260px] w-full" /></div>;
  if (channels.error) return <ErrorState title="无法加载 OpenClaw 原生 Channel" description={channels.error.message} />;
  const setField = (key: keyof ChannelDraft) => (value: string) => setDraft((prev) => ({ ...prev, [key]: value }));
  const payload = () => ({ enabled: draft.enabled, groupPolicy: draft.groupPolicy, streaming: draft.streaming, dmPolicy: draft.dmPolicy, responsePrefix: draft.responsePrefix, threadBindings: { enabled: draft.threadEnabled, idleHours: Number(draft.threadIdleHours) || 24, maxAgeHours: Number(draft.threadMaxAgeHours) || 0, spawnSessions: draft.threadSpawnSessions } });
  const save = () => {
    if (!draft.type.trim()) return toast.error("Channel 类型不能为空");
    if (mode === "new") createChannel.mutate({ type: draft.type.trim(), enabled: draft.enabled }, { onSuccess: () => { updateChannel.mutate({ type: draft.type.trim(), payload: payload() }); toast.success("OpenClaw Channel 已新增"); setMode("edit"); setSelectedKey(draft.type.trim()); }, onError: (error) => toast.error("新增失败", { description: error.message }) });
    else updateChannel.mutate({ type: draft.type, payload: payload() }, { onSuccess: () => toast.success("OpenClaw Channel 已保存"), onError: (error) => toast.error("保存失败", { description: error.message }) });
  };
  const remove = () => { if (!selected) return; if (!window.confirm(`删除 OpenClaw Channel '${selected.type}'？相关 OpenClaw 静态绑定也会移除。`)) return; deleteChannel.mutate(selected.type, { onSuccess: () => toast.success("OpenClaw Channel 已删除"), onError: (error) => toast.error("删除失败", { description: error.message }) }); };
  return <div className="grid gap-[18px]">
    <section className="rounded-md border border-line bg-panel shadow-sm"><WorkbenchToolbar title="OpenClaw 原生 Channel" description="管理上游 channels：新增、编辑、启停和删除。Tracevane IM 渠道只管理投递与运行态。"><SearchBox value={query} onChange={setQuery} placeholder="搜索 OpenClaw channel" /><Button size="sm" onClick={() => { setMode("new"); setDraft(emptyDraft); }}>新增 Channel</Button><RefreshButton loading={channels.isFetching} onClick={() => { void channels.refetch(); }} /><BoundaryBadge /></WorkbenchToolbar><div className="grid gap-[18px] p-3 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="grid gap-3"><div className="grid gap-3 md:grid-cols-4"><StatTile label="原生渠道" value={channels.data?.counts.channels ?? 0} sub="OpenClaw 上游" /><StatTile label="原生账号" value={channels.data?.counts.accounts ?? 0} sub="OpenClaw accounts" /><StatTile label="静态绑定" value={channels.data?.counts.bindings ?? 0} sub="OpenClaw bindings" /><StatTile label="当前编辑" value={mode === "new" ? "新增" : selected?.type ?? "—"} sub="OpenClaw 原生配置" /></div><ResponsiveTable columns={["OpenClaw channel", "原生账号", "静态绑定", "状态"]} rows={filtered.map((channel) => <SelectableRow key={channel.type} id={channel.type} selected={mode === "edit" && selectedKey === channel.type} onSelect={(id) => { setMode("edit"); setSelectedKey(id); }}><td className="max-w-[260px] truncate px-4 py-3"><div className="font-medium text-ink-strong">{channel.type}</div><div className="text-xs text-muted">OpenClaw 上游</div></td><td className="px-4 py-3 text-muted">{channel.accountCount}</td><td className="px-4 py-3 text-muted">{channel.bindingCount}</td><td className="px-4 py-3"><StatusPill tone={channel.enabled ? "ok" : "warn"}>{channel.enabled ? "已启用" : "已停用"}</StatusPill></td></SelectableRow>)} empty="无匹配 OpenClaw Channel" /></div><DetailRail title={selected?.type ?? "未选择 Channel"} subtitle="OpenClaw 上游证据"><EvidenceRow label="原生账号" value={selected?.accountCount ?? "—"} /><EvidenceRow label="静态绑定" value={selected?.bindingCount ?? "—"} /><EvidenceRow label="DM 策略" value={selected?.dmPolicy ?? "—"} /></DetailRail></div></section>
    <section className="rounded-md border border-line bg-panel shadow-sm"><PanelHead title={mode === "new" ? "新增 OpenClaw Channel" : `编辑 ${draft.type || "Channel"}`} sub="这里修改 OpenClaw channels.<type> 常用字段；账号密钥仍通过账号表单/IM 域处理。" /><div className="grid gap-3 p-4 md:grid-cols-2 xl:grid-cols-3"><TextInput label="Channel 类型" value={draft.type} onChange={setField("type")} disabled={mode === "edit"} /><ToggleInput label="启用 Channel" checked={draft.enabled} onChange={(enabled) => setDraft((prev) => ({ ...prev, enabled }))} /><SelectInput label="群组策略" value={draft.groupPolicy} onChange={setField("groupPolicy")} options={["open", "allowlist", "disabled"]} /><SelectInput label="私聊策略" value={draft.dmPolicy} onChange={setField("dmPolicy")} options={["open", "allowlist", "disabled"]} /><SelectInput label="流式推送" value={draft.streaming} onChange={setField("streaming")} options={["off", "partial", "final"]} /><TextInput label="回复前缀" value={draft.responsePrefix} onChange={setField("responsePrefix")} /><ToggleInput label="启用线程绑定" checked={draft.threadEnabled} onChange={(threadEnabled) => setDraft((prev) => ({ ...prev, threadEnabled }))} /><ToggleInput label="线程自动生成会话" checked={draft.threadSpawnSessions} onChange={(threadSpawnSessions) => setDraft((prev) => ({ ...prev, threadSpawnSessions }))} /><TextInput label="线程空闲小时" type="number" value={draft.threadIdleHours} onChange={setField("threadIdleHours")} /><TextInput label="线程最大保留小时" type="number" value={draft.threadMaxAgeHours} onChange={setField("threadMaxAgeHours")} /></div><div className="flex flex-wrap gap-2 border-t border-line px-4 py-3"><Button size="sm" onClick={save} disabled={createChannel.isPending || updateChannel.isPending}>{mode === "new" ? "新增" : "保存"}</Button>{mode === "edit" ? <Button variant="outline" size="sm" onClick={remove} disabled={!selected || deleteChannel.isPending}>删除</Button> : <Button variant="ghost" size="sm" onClick={() => setMode("edit")}>取消新增</Button>}</div></section>
  </div>;
}
